// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDieselSchemaMigration = "__diesel_schema_migrations"

// DieselSchemaMigration mapped from table <__diesel_schema_migrations>
type DieselSchemaMigration struct {
	Version string    `gorm:"column:version;primaryKey" json:"version"`
	RunOn   time.Time `gorm:"column:run_on;not null;default:CURRENT_TIMESTAMP" json:"run_on"`
}

// TableName DieselSchemaMigration's table name
func (*DieselSchemaMigration) TableName() string {
	return TableNameDieselSchemaMigration
}
