// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameAccessory = "accessories"

// Accessory mapped from table <accessories>
type Accessory struct {
	ID          uuid.UUID  `gorm:"column:id;primaryKey" json:"id"`
	Character   *uuid.UUID `gorm:"column:character" json:"character"`
	Name        string     `gorm:"column:name;not null" json:"name"`
	Description *string    `gorm:"column:description" json:"description"`
}

// TableName Accessory's table name
func (*Accessory) TableName() string {
	return TableNameAccessory
}
