// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameCharacterrel = "characterrel"

// Characterrel mapped from table <characterrel>
type Characterrel struct {
	ID         *uuid.UUID `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	EdgeWeight *string    `gorm:"column:edge_weight;type:text" json:"edge_weight"`
	Character  *uuid.UUID `gorm:"column:character;type:uuid" json:"character"`
	Other      *uuid.UUID `gorm:"column:other;type:uuid" json:"other"`
}

// TableName Characterrel's table name
func (*Characterrel) TableName() string {
	return TableNameCharacterrel
}
