// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCharacterFragment = "character_fragments"

// CharacterFragment mapped from table <character_fragments>
type CharacterFragment struct {
	Character string `gorm:"column:character;primaryKey" json:"character"`
	Fragment  string `gorm:"column:fragment;primaryKey" json:"fragment"`
}

// TableName CharacterFragment's table name
func (*CharacterFragment) TableName() string {
	return TableNameCharacterFragment
}
