// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCharacterrel = "characterrel"

// Characterrel mapped from table <characterrel>
type Characterrel struct {
	ID         string `gorm:"column:id;primaryKey" json:"id"`
	EdgeWeight string `gorm:"column:edge_weight" json:"edge_weight"`
	Character  string `gorm:"column:character" json:"character"`
	Other      string `gorm:"column:other" json:"other"`
}

// TableName Characterrel's table name
func (*Characterrel) TableName() string {
	return TableNameCharacterrel
}
