// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCharacterfragment = "characterfragments"

// Characterfragment mapped from table <characterfragments>
type Characterfragment struct {
	Character string `gorm:"column:character;primaryKey" json:"character"`
	Fragment  string `gorm:"column:fragment;primaryKey" json:"fragment"`
}

// TableName Characterfragment's table name
func (*Characterfragment) TableName() string {
	return TableNameCharacterfragment
}
