// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameCharacter = "characters"

// Character mapped from table <characters>
type Character struct {
	ID          **uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Name        string      `gorm:"column:name;type:text;not null" json:"name"`
	Description *string     `gorm:"column:description;type:text" json:"description"`
	Metadata    *uuid.UUID  `gorm:"column:metadata;type:uuid" json:"metadata"`
	Created     *int64      `gorm:"column:created;type:bigint;default:unix_now()" json:"created"`
	LastEdited  *int64      `gorm:"column:last_edited;type:bigint;default:unix_now()" json:"last_edited"`
	Thumbnail   *uuid.UUID  `gorm:"column:thumbnail;type:uuid" json:"thumbnail"`
	Gender      *string     `gorm:"column:gender;type:text;not null;default:female" json:"gender"`
}

// TableName Character's table name
func (*Character) TableName() string {
	return TableNameCharacter
}
