// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameEdit = "edits"

// Edit mapped from table <edits>
type Edit struct {
	ID        uuid.UUID  `gorm:"column:id;primaryKey" json:"id"`
	Date      *int64     `gorm:"column:date" json:"date"`
	Editor    *uuid.UUID `gorm:"column:editor" json:"editor"`
	Comment   *string    `gorm:"column:comment" json:"comment"`
	Value     string     `gorm:"column:value;not null" json:"value"`
	Prevvalue string     `gorm:"column:prevvalue;not null" json:"prevvalue"`
	Entity    *uuid.UUID `gorm:"column:entity" json:"entity"`
	Field     string     `gorm:"column:field;not null" json:"field"`
	Change    string     `gorm:"column:change;not null" json:"change"`
	UpdateID  *uuid.UUID `gorm:"column:update_id" json:"update_id"`
	Line      *int64     `gorm:"column:line" json:"line"`
}

// TableName Edit's table name
func (*Edit) TableName() string {
	return TableNameEdit
}
