// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEdit = "edits"

// Edit mapped from table <edits>
type Edit struct {
	ID        string `gorm:"column:id;primaryKey" json:"id"`
	Date      int64  `gorm:"column:date" json:"date"`
	Editor    string `gorm:"column:editor" json:"editor"`
	Comment   string `gorm:"column:comment" json:"comment"`
	Value     string `gorm:"column:value;not null" json:"value"`
	Prevvalue string `gorm:"column:prevvalue" json:"prevvalue"`
	Change    string `gorm:"column:change" json:"change"`
}

// TableName Edit's table name
func (*Edit) TableName() string {
	return TableNameEdit
}
