// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameEntity = "entities"

// Entity mapped from table <entities>
type Entity struct {
	ID          uuid.UUID  `gorm:"column:id;primaryKey" json:"id"`
	Active      *bool      `gorm:"column:active;default:true" json:"active"`
	GroupID     *uuid.UUID `gorm:"column:group_id" json:"group_id"`
	Created     int64      `gorm:"column:created;not null;default:unix_now()" json:"created"`
	Description *string    `gorm:"column:description" json:"description"`
	Name        *string    `gorm:"column:name" json:"name"`
}

// TableName Entity's table name
func (*Entity) TableName() string {
	return TableNameEntity
}
