// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEntityrel = "entityrel"

// Entityrel mapped from table <entityrel>
type Entityrel struct {
	ID           string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	SourceEntity string `gorm:"column:source_entity;not null" json:"source_entity"`
	TargetEntity string `gorm:"column:target_entity;not null" json:"target_entity"`
	RelationType string `gorm:"column:relation_type;not null" json:"relation_type"`
	Description  string `gorm:"column:description" json:"description"`
}

// TableName Entityrel's table name
func (*Entityrel) TableName() string {
	return TableNameEntityrel
}
