// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameEntityGroup = "entity_groups"

// EntityGroup mapped from table <entity_groups>
type EntityGroup struct {
	EntityID uuid.UUID `gorm:"column:entity_id;primaryKey" json:"entity_id"`
	GroupID  uuid.UUID `gorm:"column:group_id;primaryKey" json:"group_id"`
}

// TableName EntityGroup's table name
func (*EntityGroup) TableName() string {
	return TableNameEntityGroup
}
