// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameEntity = "entities"

// Entity mapped from table <entities>
type Entity struct {
	ID      *uuid.UUID `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	Active  *bool      `gorm:"column:active;type:boolean;default:true" json:"active"`
	GroupID *uuid.UUID `gorm:"column:group_id;type:uuid" json:"group_id"`
}

// TableName Entity's table name
func (*Entity) TableName() string {
	return TableNameEntity
}
