// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameExifTag = "exif_tags"

// ExifTag mapped from table <exif_tags>
type ExifTag struct {
	ID    string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Image string `gorm:"column:image" json:"image"`
	Tag   int32  `gorm:"column:tag;not null" json:"tag"`
	Value string `gorm:"column:value;not null" json:"value"`
}

// TableName ExifTag's table name
func (*ExifTag) TableName() string {
	return TableNameExifTag
}
