// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameFragment = "fragments"

// Fragment mapped from table <fragments>
type Fragment struct {
	ID          *uuid.UUID `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	Metadata    *uuid.UUID `gorm:"column:metadata;type:uuid" json:"metadata"`
	Idx         int32      `gorm:"column:idx;type:integer;not null" json:"idx"`
	Content     string     `gorm:"column:content;type:text;not null" json:"content"`
	Name        string     `gorm:"column:name;type:text;not null" json:"name"`
	LastEdited  *int64     `gorm:"column:last_edited;type:bigint;default:unix_now()" json:"last_edited"`
	Created     *int64     `gorm:"column:created;type:bigint;default:unix_now()" json:"created"`
	Description *string    `gorm:"column:description;type:text" json:"description"`
}

// TableName Fragment's table name
func (*Fragment) TableName() string {
	return TableNameFragment
}
