// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFragmentImage = "fragment_images"

// FragmentImage mapped from table <fragment_images>
type FragmentImage struct {
	Fragment string `gorm:"column:fragment;primaryKey" json:"fragment"`
	Image    string `gorm:"column:image;primaryKey" json:"image"`
}

// TableName FragmentImage's table name
func (*FragmentImage) TableName() string {
	return TableNameFragmentImage
}
