// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGraph = "graphs"

// Graph mapped from table <graphs>
type Graph struct {
	ID       string `gorm:"column:id;primaryKey" json:"id"`
	Entity   string `gorm:"column:entity" json:"entity"`
	Rendered int64  `gorm:"column:rendered;default:unix_now()" json:"rendered"`
	DotData  string `gorm:"column:dot_data;not null" json:"dot_data"`
	Created  int64  `gorm:"column:created;default:unix_now()" json:"created"`
}

// TableName Graph's table name
func (*Graph) TableName() string {
	return TableNameGraph
}
