// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameGroup = "groups"

// Group mapped from table <groups>
type Group struct {
	ID          uuid.UUID `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name        *string   `gorm:"column:name" json:"name"`
	Description *string   `gorm:"column:description" json:"description"`
	Permissions *string   `gorm:"column:permissions;default:ARRAY['create" json:"permissions"`
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
