// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameGrouprel = "grouprel"

// Grouprel mapped from table <grouprel>
type Grouprel struct {
	ID          **uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	GroupID     *uuid.UUID  `gorm:"column:group_id;type:uuid" json:"group_id"`
	UserID      *uuid.UUID  `gorm:"column:user_id;type:uuid" json:"user_id"`
	Description *string     `gorm:"column:description;type:text" json:"description"`
}

// TableName Grouprel's table name
func (*Grouprel) TableName() string {
	return TableNameGrouprel
}
