// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameGroupPermission = "group_permissions"

// GroupPermission mapped from table <group_permissions>
type GroupPermission struct {
	GroupID    uuid.UUID `gorm:"column:group_id;not null" json:"group_id"`
	Permission string    `gorm:"column:permission;not null" json:"permission"`
	Propagate  bool      `gorm:"column:propagate;not null" json:"propagate"`
}

// TableName GroupPermission's table name
func (*GroupPermission) TableName() string {
	return TableNameGroupPermission
}
