// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameGroup = "groups"

// Group mapped from table <groups>
type Group struct {
	ID          **uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Name        *string     `gorm:"column:name;type:text" json:"name"`
	Description *string     `gorm:"column:description;type:text" json:"description"`
	Permissions *string     `gorm:"column:permissions;type:text[];default:ARRAY['create" json:"permissions"`
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
