// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGrouprel = "grouprel"

// Grouprel mapped from table <grouprel>
type Grouprel struct {
	ID          string `gorm:"column:id;primaryKey" json:"id"`
	GroupID     string `gorm:"column:group_id" json:"group_id"`
	UserID      string `gorm:"column:user_id" json:"user_id"`
	Description string `gorm:"column:description" json:"description"`
}

// TableName Grouprel's table name
func (*Grouprel) TableName() string {
	return TableNameGrouprel
}
