// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameGroupClosure = "group_closure"

// GroupClosure mapped from table <group_closure>
type GroupClosure struct {
	AncestorID   uuid.UUID `gorm:"column:ancestor_id;primaryKey" json:"ancestor_id"`
	DescendantID uuid.UUID `gorm:"column:descendant_id;primaryKey" json:"descendant_id"`
	Depth        int32     `gorm:"column:depth;not null" json:"depth"`
}

// TableName GroupClosure's table name
func (*GroupClosure) TableName() string {
	return TableNameGroupClosure
}
