// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameGrouprel = "grouprel"

// Grouprel mapped from table <grouprel>
type Grouprel struct {
	ID          uuid.UUID  `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	GroupID     *uuid.UUID `gorm:"column:group_id" json:"group_id"`
	UserID      *uuid.UUID `gorm:"column:user_id" json:"user_id"`
	Description *string    `gorm:"column:description" json:"description"`
}

// TableName Grouprel's table name
func (*Grouprel) TableName() string {
	return TableNameGrouprel
}
