// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameGroupRel = "group_rel"

// GroupRel mapped from table <group_rel>
type GroupRel struct {
	ID          uuid.UUID `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	GroupID     uuid.UUID `gorm:"column:group_id;not null" json:"group_id"`
	UserID      uuid.UUID `gorm:"column:user_id;not null" json:"user_id"`
	Description *string   `gorm:"column:description" json:"description"`
}

// TableName GroupRel's table name
func (*GroupRel) TableName() string {
	return TableNameGroupRel
}
