// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameGroup = "groups"

// Group mapped from table <groups>
type Group struct {
	ID          uuid.UUID  `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name        *string    `gorm:"column:name" json:"name"`
	Description *string    `gorm:"column:description" json:"description"`
	Hidden      bool       `gorm:"column:hidden;not null" json:"hidden"`
	ParentID    *uuid.UUID `gorm:"column:parent_id" json:"parent_id"`
	Created     int64      `gorm:"column:created;not null;default:unix_now()" json:"created"`
	Private     *bool      `gorm:"column:private" json:"private"`
	Archive     bool       `gorm:"column:archive;not null" json:"archive"`
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
