// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameImage = "images"

// Image mapped from table <images>
type Image struct {
	ID          uuid.UUID `gorm:"column:id;primaryKey" json:"id"`
	URL         string    `gorm:"column:url;not null" json:"url"`
	Description *string   `gorm:"column:description" json:"description"`
}

// TableName Image's table name
func (*Image) TableName() string {
	return TableNameImage
}
