// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameImagetag = "imagetags"

// Imagetag mapped from table <imagetags>
type Imagetag struct {
	ID    string  `gorm:"column:id;primaryKey" json:"id"`
	Image string  `gorm:"column:image" json:"image"`
	Tag   int32   `gorm:"column:tag" json:"tag"`
	Value []uint8 `gorm:"column:value" json:"value"`
}

// TableName Imagetag's table name
func (*Imagetag) TableName() string {
	return TableNameImagetag
}
