// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameImage = "images"

// Image mapped from table <images>
type Image struct {
	ID          string `gorm:"column:id;primaryKey" json:"id"`
	Metadata    string `gorm:"column:metadata" json:"metadata"`
	URL         string `gorm:"column:url;not null" json:"url"`
	Description string `gorm:"column:description" json:"description"`
}

// TableName Image's table name
func (*Image) TableName() string {
	return TableNameImage
}
