// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameLicense = "licenses"

// License mapped from table <licenses>
type License struct {
	ID          *uuid.UUID `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	Name        string     `gorm:"column:name;type:text;not null" json:"name"`
	Description *string    `gorm:"column:description;type:text" json:"description"`
	Public      *bool      `gorm:"column:public;type:boolean" json:"public"`
	Content     *string    `gorm:"column:content;type:text" json:"content"`
}

// TableName License's table name
func (*License) TableName() string {
	return TableNameLicense
}
