// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLocationfragment = "locationfragments"

// Locationfragment mapped from table <locationfragments>
type Locationfragment struct {
	Location string `gorm:"column:location;primaryKey" json:"location"`
	Fragment string `gorm:"column:fragment;primaryKey" json:"fragment"`
}

// TableName Locationfragment's table name
func (*Locationfragment) TableName() string {
	return TableNameLocationfragment
}
