// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLocationFragment = "location_fragments"

// LocationFragment mapped from table <location_fragments>
type LocationFragment struct {
	Location string `gorm:"column:location;primaryKey" json:"location"`
	Fragment string `gorm:"column:fragment;primaryKey" json:"fragment"`
}

// TableName LocationFragment's table name
func (*LocationFragment) TableName() string {
	return TableNameLocationFragment
}
