// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameLocation = "locations"

// Location mapped from table <locations>
type Location struct {
	ID          *uuid.UUID `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	Name        string     `gorm:"column:name;type:text;not null" json:"name"`
	Description *string    `gorm:"column:description;type:text" json:"description"`
	Created     *int64     `gorm:"column:created;type:bigint;default:unix_now()" json:"created"`
	Thumbnail   *uuid.UUID `gorm:"column:thumbnail;type:uuid" json:"thumbnail"`
	LastEdited  *int64     `gorm:"column:last_edited;type:bigint;default:unix_now()" json:"last_edited"`
}

// TableName Location's table name
func (*Location) TableName() string {
	return TableNameLocation
}
