// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLocation = "locations"

// Location mapped from table <locations>
type Location struct {
	ID          string `gorm:"column:id;primaryKey" json:"id"`
	Timeline    string `gorm:"column:timeline" json:"timeline"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Description string `gorm:"column:description" json:"description"`
	Metadata    string `gorm:"column:metadata" json:"metadata"`
}

// TableName Location's table name
func (*Location) TableName() string {
	return TableNameLocation
}
