// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameMap = "maps"

// Map mapped from table <maps>
type Map struct {
	ID        uuid.UUID  `gorm:"column:id;primaryKey" json:"id"`
	Location  *uuid.UUID `gorm:"column:location" json:"location"`
	Latitude  *int64     `gorm:"column:latitude" json:"latitude"`
	Longitude *int64     `gorm:"column:longitude" json:"longitude"`
	Radius    *int64     `gorm:"column:radius" json:"radius"`
}

// TableName Map's table name
func (*Map) TableName() string {
	return TableNameMap
}
