// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMetadatum = "metadata"

// Metadatum mapped from table <metadata>
type Metadatum struct {
	ID      string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Creator string `gorm:"column:creator" json:"creator"`
	License string `gorm:"column:license" json:"license"`
	Shared  string `gorm:"column:shared" json:"shared"`
	Public  bool   `gorm:"column:public" json:"public"`
	Active  bool   `gorm:"column:active;default:true" json:"active"`
}

// TableName Metadatum's table name
func (*Metadatum) TableName() string {
	return TableNameMetadatum
}
