// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameMoment = "moments"

// Moment mapped from table <moments>
type Moment struct {
	ID       uuid.UUID  `gorm:"column:id;primaryKey" json:"id"`
	Timeline uuid.UUID  `gorm:"column:timeline;not null" json:"timeline"`
	Idx      int64      `gorm:"column:idx;not null" json:"idx"`
	Fragment *uuid.UUID `gorm:"column:fragment" json:"fragment"`
}

// TableName Moment's table name
func (*Moment) TableName() string {
	return TableNameMoment
}
