// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMoment = "moments"

// Moment mapped from table <moments>
type Moment struct {
	ID       string `gorm:"column:id;primaryKey" json:"id"`
	Timeline string `gorm:"column:timeline" json:"timeline"`
	Idx      int64  `gorm:"column:idx;not null" json:"idx"`
	Fragment string `gorm:"column:fragment" json:"fragment"`
}

// TableName Moment's table name
func (*Moment) TableName() string {
	return TableNameMoment
}
