// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameOrganization = "organizations"

// Organization mapped from table <organizations>
type Organization struct {
	ID          uuid.UUID `gorm:"column:id;primaryKey" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description *string   `gorm:"column:description" json:"description"`
	Created     *int64    `gorm:"column:created;default:unix_now()" json:"created"`
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
