// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameRecording = "recordings"

// Recording mapped from table <recordings>
type Recording struct {
	ID          **uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Title       *string     `gorm:"column:title;type:text" json:"title"`
	Artist      *string     `gorm:"column:artist;type:text" json:"artist"`
	Album       *string     `gorm:"column:album;type:text" json:"album"`
	Genre       *string     `gorm:"column:genre;type:text" json:"genre"`
	Year        *int32      `gorm:"column:year;type:integer" json:"year"`
	TrackNumber *int32      `gorm:"column:track_number;type:integer" json:"track_number"`
	DiscNumber  *int32      `gorm:"column:disc_number;type:integer" json:"disc_number"`
	AlbumArtist *string     `gorm:"column:album_artist;type:text" json:"album_artist"`
	Comment     *string     `gorm:"column:comment;type:text" json:"comment"`
	Composer    *string     `gorm:"column:composer;type:text" json:"composer"`
	Lyrics      *string     `gorm:"column:lyrics;type:text" json:"lyrics"`
	Created     *int64      `gorm:"column:created;type:bigint;default:unix_now()" json:"created"`
	LastEditted *int64      `gorm:"column:last_editted;type:bigint;default:unix_now()" json:"last_editted"`
}

// TableName Recording's table name
func (*Recording) TableName() string {
	return TableNameRecording
}
