// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameRelation = "relations"

// Relation mapped from table <relations>
type Relation struct {
	Parent         *uuid.UUID `gorm:"column:parent;type:uuid;primaryKey" json:"parent"`
	Child          *uuid.UUID `gorm:"column:child;type:uuid;primaryKey" json:"child"`
	Description    *string    `gorm:"column:description;type:text" json:"description"`
	ParentCategory string     `gorm:"column:parent_category;type:text;primaryKey" json:"parent_category"`
	ChildCategory  string     `gorm:"column:child_category;type:text;primaryKey" json:"child_category"`
}

// TableName Relation's table name
func (*Relation) TableName() string {
	return TableNameRelation
}
