// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameRelation = "relations"

// Relation mapped from table <relations>
type Relation struct {
	Parent         uuid.UUID  `gorm:"column:parent;primaryKey" json:"parent"`
	Child          uuid.UUID  `gorm:"column:child;primaryKey" json:"child"`
	Description    *string    `gorm:"column:description" json:"description"`
	ParentCategory string     `gorm:"column:parent_category;primaryKey" json:"parent_category"`
	ChildCategory  string     `gorm:"column:child_category;primaryKey" json:"child_category"`
	Root           *uuid.UUID `gorm:"column:root" json:"root"`
}

// TableName Relation's table name
func (*Relation) TableName() string {
	return TableNameRelation
}
