// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStoryFragment = "story_fragments"

// StoryFragment mapped from table <story_fragments>
type StoryFragment struct {
	Story    string `gorm:"column:story;primaryKey" json:"story"`
	Fragment string `gorm:"column:fragment;primaryKey" json:"fragment"`
}

// TableName StoryFragment's table name
func (*StoryFragment) TableName() string {
	return TableNameStoryFragment
}
