// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStoryfragment = "storyfragments"

// Storyfragment mapped from table <storyfragments>
type Storyfragment struct {
	Story    string `gorm:"column:story;primaryKey" json:"story"`
	Fragment string `gorm:"column:fragment;primaryKey" json:"fragment"`
}

// TableName Storyfragment's table name
func (*Storyfragment) TableName() string {
	return TableNameStoryfragment
}
