// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStory = "stories"

// Story mapped from table <stories>
type Story struct {
	ID          string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Timeline    string `gorm:"column:timeline" json:"timeline"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Description string `gorm:"column:description" json:"description"`
	Renderer    string `gorm:"column:renderer" json:"renderer"`
	Metadata    string `gorm:"column:metadata" json:"metadata"`
	Created     int64  `gorm:"column:created" json:"created"`
	LastEdited  int64  `gorm:"column:last_edited" json:"last_edited"`
	Image       string `gorm:"column:image" json:"image"`
}

// TableName Story's table name
func (*Story) TableName() string {
	return TableNameStory
}
