// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStory = "stories"

// Story mapped from table <stories>
type Story struct {
	ID          string  `gorm:"column:id;primaryKey" json:"id"`
	Timeline    string  `gorm:"column:timeline" json:"timeline"`
	Name        string  `gorm:"column:name;not null" json:"name"`
	Description string  `gorm:"column:description" json:"description"`
	Content     []uint8 `gorm:"column:content" json:"content"`
	Created     int64   `gorm:"column:created" json:"created"`
	LastEdited  int64   `gorm:"column:last_edited" json:"last_edited"`
	Creator     string  `gorm:"column:creator" json:"creator"`
	License     string  `gorm:"column:license" json:"license"`
	Shared      string  `gorm:"column:shared" json:"shared"`
	Renderer    string  `gorm:"column:renderer" json:"renderer"`
	Public      bool    `gorm:"column:public" json:"public"`
}

// TableName Story's table name
func (*Story) TableName() string {
	return TableNameStory
}
