// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTask = "tasks"

// Task mapped from table <tasks>
type Task struct {
	ID          string `gorm:"column:id;primaryKey" json:"id"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Description string `gorm:"column:description" json:"description"`
	Created     int64  `gorm:"column:created;default:unix_now()" json:"created"`
	Completed   int64  `gorm:"column:completed" json:"completed"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
