// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameTimeline = "timelines"

// Timeline mapped from table <timelines>
type Timeline struct {
	ID          uuid.UUID  `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Created     *int64     `gorm:"column:created" json:"created"`
	LastEdited  *int64     `gorm:"column:last_edited" json:"last_edited"`
	Description *string    `gorm:"column:description" json:"description"`
	Name        string     `gorm:"column:name;not null;default:default" json:"name"`
	Source      *uuid.UUID `gorm:"column:source" json:"source"`
}

// TableName Timeline's table name
func (*Timeline) TableName() string {
	return TableNameTimeline
}
