// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameTimeline = "timelines"

// Timeline mapped from table <timelines>
type Timeline struct {
	ID          **uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Created     *int64      `gorm:"column:created;type:bigint" json:"created"`
	LastEdited  *int64      `gorm:"column:last_edited;type:bigint" json:"last_edited"`
	Description *string     `gorm:"column:description;type:text" json:"description"`
	Name        *string     `gorm:"column:name;type:text;not null;default:default" json:"name"`
	Source      *uuid.UUID  `gorm:"column:source;type:uuid" json:"source"`
}

// TableName Timeline's table name
func (*Timeline) TableName() string {
	return TableNameTimeline
}
