// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTimeline = "timelines"

// Timeline mapped from table <timelines>
type Timeline struct {
	ID         string `gorm:"column:id;primaryKey" json:"id"`
	Created    int64  `gorm:"column:created" json:"created"`
	LastEdited int64  `gorm:"column:last_edited" json:"last_edited"`
	Creator    string `gorm:"column:creator" json:"creator"`
	License    string `gorm:"column:license" json:"license"`
	Shared     string `gorm:"column:shared" json:"shared"`
}

// TableName Timeline's table name
func (*Timeline) TableName() string {
	return TableNameTimeline
}
