// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameUniverse = "universe"

// Universe mapped from table <universe>
type Universe struct {
	ID          **uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	Name        string      `gorm:"column:name;type:text;not null" json:"name"`
	Description *string     `gorm:"column:description;type:text" json:"description"`
	Metadata    *uuid.UUID  `gorm:"column:metadata;type:uuid" json:"metadata"`
	Created     *int64      `gorm:"column:created;type:bigint" json:"created"`
	LastEdited  *int64      `gorm:"column:last_edited;type:bigint" json:"last_edited"`
}

// TableName Universe's table name
func (*Universe) TableName() string {
	return TableNameUniverse
}
