// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

const TableNameUniverse = "universe"

// Universe mapped from table <universe>
type Universe struct {
	ID          uuid.UUID  `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name        string     `gorm:"column:name;not null" json:"name"`
	Description *string    `gorm:"column:description" json:"description"`
	Metadata    *uuid.UUID `gorm:"column:metadata" json:"metadata"`
	Created     *int64     `gorm:"column:created" json:"created"`
	LastEdited  *int64     `gorm:"column:last_edited" json:"last_edited"`
}

// TableName Universe's table name
func (*Universe) TableName() string {
	return TableNameUniverse
}
