// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUniverse = "universe"

// Universe mapped from table <universe>
type Universe struct {
	ID          string `gorm:"column:id;primaryKey" json:"id"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Description string `gorm:"column:description" json:"description"`
	Created     int64  `gorm:"column:created" json:"created"`
	LastEdited  int64  `gorm:"column:last_edited" json:"last_edited"`
	Creator     string `gorm:"column:creator" json:"creator"`
	License     string `gorm:"column:license" json:"license"`
	Shared      string `gorm:"column:shared" json:"shared"`
}

// TableName Universe's table name
func (*Universe) TableName() string {
	return TableNameUniverse
}
