// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUsergroup = "usergroups"

// Usergroup mapped from table <usergroups>
type Usergroup struct {
	ID          string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name        string `gorm:"column:name" json:"name"`
	Description string `gorm:"column:description" json:"description"`
}

// TableName Usergroup's table name
func (*Usergroup) TableName() string {
	return TableNameUsergroup
}
