// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vivianlazaras/storyteller/model"
)

func newCharacterrel(db *gorm.DB, opts ...gen.DOOption) characterrel {
	_characterrel := characterrel{}

	_characterrel.characterrelDo.UseDB(db, opts...)
	_characterrel.characterrelDo.UseModel(&model.Characterrel{})

	tableName := _characterrel.characterrelDo.TableName()
	_characterrel.ALL = field.NewAsterisk(tableName)
	_characterrel.ID = field.NewField(tableName, "id")
	_characterrel.EdgeWeight = field.NewString(tableName, "edge_weight")
	_characterrel.Character = field.NewField(tableName, "character")
	_characterrel.Other = field.NewField(tableName, "other")

	_characterrel.fillFieldMap()

	return _characterrel
}

type characterrel struct {
	characterrelDo characterrelDo

	ALL        field.Asterisk
	ID         field.Field
	EdgeWeight field.String
	Character  field.Field
	Other      field.Field

	fieldMap map[string]field.Expr
}

func (c characterrel) Table(newTableName string) *characterrel {
	c.characterrelDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c characterrel) As(alias string) *characterrel {
	c.characterrelDo.DO = *(c.characterrelDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *characterrel) updateTableName(table string) *characterrel {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewField(table, "id")
	c.EdgeWeight = field.NewString(table, "edge_weight")
	c.Character = field.NewField(table, "character")
	c.Other = field.NewField(table, "other")

	c.fillFieldMap()

	return c
}

func (c *characterrel) WithContext(ctx context.Context) *characterrelDo {
	return c.characterrelDo.WithContext(ctx)
}

func (c characterrel) TableName() string { return c.characterrelDo.TableName() }

func (c characterrel) Alias() string { return c.characterrelDo.Alias() }

func (c characterrel) Columns(cols ...field.Expr) gen.Columns {
	return c.characterrelDo.Columns(cols...)
}

func (c *characterrel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *characterrel) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 4)
	c.fieldMap["id"] = c.ID
	c.fieldMap["edge_weight"] = c.EdgeWeight
	c.fieldMap["character"] = c.Character
	c.fieldMap["other"] = c.Other
}

func (c characterrel) clone(db *gorm.DB) characterrel {
	c.characterrelDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c characterrel) replaceDB(db *gorm.DB) characterrel {
	c.characterrelDo.ReplaceDB(db)
	return c
}

type characterrelDo struct{ gen.DO }

func (c characterrelDo) Debug() *characterrelDo {
	return c.withDO(c.DO.Debug())
}

func (c characterrelDo) WithContext(ctx context.Context) *characterrelDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c characterrelDo) ReadDB() *characterrelDo {
	return c.Clauses(dbresolver.Read)
}

func (c characterrelDo) WriteDB() *characterrelDo {
	return c.Clauses(dbresolver.Write)
}

func (c characterrelDo) Session(config *gorm.Session) *characterrelDo {
	return c.withDO(c.DO.Session(config))
}

func (c characterrelDo) Clauses(conds ...clause.Expression) *characterrelDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c characterrelDo) Returning(value interface{}, columns ...string) *characterrelDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c characterrelDo) Not(conds ...gen.Condition) *characterrelDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c characterrelDo) Or(conds ...gen.Condition) *characterrelDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c characterrelDo) Select(conds ...field.Expr) *characterrelDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c characterrelDo) Where(conds ...gen.Condition) *characterrelDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c characterrelDo) Order(conds ...field.Expr) *characterrelDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c characterrelDo) Distinct(cols ...field.Expr) *characterrelDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c characterrelDo) Omit(cols ...field.Expr) *characterrelDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c characterrelDo) Join(table schema.Tabler, on ...field.Expr) *characterrelDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c characterrelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *characterrelDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c characterrelDo) RightJoin(table schema.Tabler, on ...field.Expr) *characterrelDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c characterrelDo) Group(cols ...field.Expr) *characterrelDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c characterrelDo) Having(conds ...gen.Condition) *characterrelDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c characterrelDo) Limit(limit int) *characterrelDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c characterrelDo) Offset(offset int) *characterrelDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c characterrelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *characterrelDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c characterrelDo) Unscoped() *characterrelDo {
	return c.withDO(c.DO.Unscoped())
}

func (c characterrelDo) Create(values ...*model.Characterrel) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c characterrelDo) CreateInBatches(values []*model.Characterrel, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c characterrelDo) Save(values ...*model.Characterrel) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c characterrelDo) First() (*model.Characterrel, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Characterrel), nil
	}
}

func (c characterrelDo) Take() (*model.Characterrel, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Characterrel), nil
	}
}

func (c characterrelDo) Last() (*model.Characterrel, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Characterrel), nil
	}
}

func (c characterrelDo) Find() ([]*model.Characterrel, error) {
	result, err := c.DO.Find()
	return result.([]*model.Characterrel), err
}

func (c characterrelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Characterrel, err error) {
	buf := make([]*model.Characterrel, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c characterrelDo) FindInBatches(result *[]*model.Characterrel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c characterrelDo) Attrs(attrs ...field.AssignExpr) *characterrelDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c characterrelDo) Assign(attrs ...field.AssignExpr) *characterrelDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c characterrelDo) Joins(fields ...field.RelationField) *characterrelDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c characterrelDo) Preload(fields ...field.RelationField) *characterrelDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c characterrelDo) FirstOrInit() (*model.Characterrel, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Characterrel), nil
	}
}

func (c characterrelDo) FirstOrCreate() (*model.Characterrel, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Characterrel), nil
	}
}

func (c characterrelDo) FindByPage(offset int, limit int) (result []*model.Characterrel, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c characterrelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c characterrelDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c characterrelDo) Delete(models ...*model.Characterrel) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *characterrelDo) withDO(do gen.Dao) *characterrelDo {
	c.DO = *do.(*gen.DO)
	return c
}
