// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vivianlazaras/storyteller/model"
)

func newEdit(db *gorm.DB, opts ...gen.DOOption) edit {
	_edit := edit{}

	_edit.editDo.UseDB(db, opts...)
	_edit.editDo.UseModel(&model.Edit{})

	tableName := _edit.editDo.TableName()
	_edit.ALL = field.NewAsterisk(tableName)
	_edit.ID = field.NewField(tableName, "id")
	_edit.Date = field.NewInt64(tableName, "date")
	_edit.Editor = field.NewField(tableName, "editor")
	_edit.Comment = field.NewString(tableName, "comment")
	_edit.Value = field.NewString(tableName, "value")
	_edit.Prevvalue = field.NewString(tableName, "prevvalue")
	_edit.Entity = field.NewField(tableName, "entity")
	_edit.Field = field.NewString(tableName, "field")
	_edit.Change = field.NewString(tableName, "change")
	_edit.UpdateID = field.NewField(tableName, "update_id")

	_edit.fillFieldMap()

	return _edit
}

type edit struct {
	editDo editDo

	ALL       field.Asterisk
	ID        field.Field
	Date      field.Int64
	Editor    field.Field
	Comment   field.String
	Value     field.String
	Prevvalue field.String
	Entity    field.Field
	Field     field.String
	Change    field.String
	UpdateID  field.Field

	fieldMap map[string]field.Expr
}

func (e edit) Table(newTableName string) *edit {
	e.editDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e edit) As(alias string) *edit {
	e.editDo.DO = *(e.editDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *edit) updateTableName(table string) *edit {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewField(table, "id")
	e.Date = field.NewInt64(table, "date")
	e.Editor = field.NewField(table, "editor")
	e.Comment = field.NewString(table, "comment")
	e.Value = field.NewString(table, "value")
	e.Prevvalue = field.NewString(table, "prevvalue")
	e.Entity = field.NewField(table, "entity")
	e.Field = field.NewString(table, "field")
	e.Change = field.NewString(table, "change")
	e.UpdateID = field.NewField(table, "update_id")

	e.fillFieldMap()

	return e
}

func (e *edit) WithContext(ctx context.Context) *editDo { return e.editDo.WithContext(ctx) }

func (e edit) TableName() string { return e.editDo.TableName() }

func (e edit) Alias() string { return e.editDo.Alias() }

func (e edit) Columns(cols ...field.Expr) gen.Columns { return e.editDo.Columns(cols...) }

func (e *edit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *edit) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 10)
	e.fieldMap["id"] = e.ID
	e.fieldMap["date"] = e.Date
	e.fieldMap["editor"] = e.Editor
	e.fieldMap["comment"] = e.Comment
	e.fieldMap["value"] = e.Value
	e.fieldMap["prevvalue"] = e.Prevvalue
	e.fieldMap["entity"] = e.Entity
	e.fieldMap["field"] = e.Field
	e.fieldMap["change"] = e.Change
	e.fieldMap["update_id"] = e.UpdateID
}

func (e edit) clone(db *gorm.DB) edit {
	e.editDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e edit) replaceDB(db *gorm.DB) edit {
	e.editDo.ReplaceDB(db)
	return e
}

type editDo struct{ gen.DO }

func (e editDo) Debug() *editDo {
	return e.withDO(e.DO.Debug())
}

func (e editDo) WithContext(ctx context.Context) *editDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e editDo) ReadDB() *editDo {
	return e.Clauses(dbresolver.Read)
}

func (e editDo) WriteDB() *editDo {
	return e.Clauses(dbresolver.Write)
}

func (e editDo) Session(config *gorm.Session) *editDo {
	return e.withDO(e.DO.Session(config))
}

func (e editDo) Clauses(conds ...clause.Expression) *editDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e editDo) Returning(value interface{}, columns ...string) *editDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e editDo) Not(conds ...gen.Condition) *editDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e editDo) Or(conds ...gen.Condition) *editDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e editDo) Select(conds ...field.Expr) *editDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e editDo) Where(conds ...gen.Condition) *editDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e editDo) Order(conds ...field.Expr) *editDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e editDo) Distinct(cols ...field.Expr) *editDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e editDo) Omit(cols ...field.Expr) *editDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e editDo) Join(table schema.Tabler, on ...field.Expr) *editDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e editDo) LeftJoin(table schema.Tabler, on ...field.Expr) *editDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e editDo) RightJoin(table schema.Tabler, on ...field.Expr) *editDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e editDo) Group(cols ...field.Expr) *editDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e editDo) Having(conds ...gen.Condition) *editDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e editDo) Limit(limit int) *editDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e editDo) Offset(offset int) *editDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e editDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *editDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e editDo) Unscoped() *editDo {
	return e.withDO(e.DO.Unscoped())
}

func (e editDo) Create(values ...*model.Edit) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e editDo) CreateInBatches(values []*model.Edit, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e editDo) Save(values ...*model.Edit) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e editDo) First() (*model.Edit, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Edit), nil
	}
}

func (e editDo) Take() (*model.Edit, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Edit), nil
	}
}

func (e editDo) Last() (*model.Edit, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Edit), nil
	}
}

func (e editDo) Find() ([]*model.Edit, error) {
	result, err := e.DO.Find()
	return result.([]*model.Edit), err
}

func (e editDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Edit, err error) {
	buf := make([]*model.Edit, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e editDo) FindInBatches(result *[]*model.Edit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e editDo) Attrs(attrs ...field.AssignExpr) *editDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e editDo) Assign(attrs ...field.AssignExpr) *editDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e editDo) Joins(fields ...field.RelationField) *editDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e editDo) Preload(fields ...field.RelationField) *editDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e editDo) FirstOrInit() (*model.Edit, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Edit), nil
	}
}

func (e editDo) FirstOrCreate() (*model.Edit, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Edit), nil
	}
}

func (e editDo) FindByPage(offset int, limit int) (result []*model.Edit, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e editDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e editDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e editDo) Delete(models ...*model.Edit) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *editDo) withDO(do gen.Dao) *editDo {
	e.DO = *do.(*gen.DO)
	return e
}
