// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vivianlazaras/storyteller/model"
)

func newEntity(db *gorm.DB, opts ...gen.DOOption) entity {
	_entity := entity{}

	_entity.entityDo.UseDB(db, opts...)
	_entity.entityDo.UseModel(&model.Entity{})

	tableName := _entity.entityDo.TableName()
	_entity.ALL = field.NewAsterisk(tableName)
	_entity.ID = field.NewField(tableName, "id")
	_entity.Active = field.NewBool(tableName, "active")
	_entity.GroupID = field.NewField(tableName, "group_id")

	_entity.fillFieldMap()

	return _entity
}

type entity struct {
	entityDo entityDo

	ALL     field.Asterisk
	ID      field.Field
	Active  field.Bool
	GroupID field.Field

	fieldMap map[string]field.Expr
}

func (e entity) Table(newTableName string) *entity {
	e.entityDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e entity) As(alias string) *entity {
	e.entityDo.DO = *(e.entityDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *entity) updateTableName(table string) *entity {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewField(table, "id")
	e.Active = field.NewBool(table, "active")
	e.GroupID = field.NewField(table, "group_id")

	e.fillFieldMap()

	return e
}

func (e *entity) WithContext(ctx context.Context) *entityDo { return e.entityDo.WithContext(ctx) }

func (e entity) TableName() string { return e.entityDo.TableName() }

func (e entity) Alias() string { return e.entityDo.Alias() }

func (e entity) Columns(cols ...field.Expr) gen.Columns { return e.entityDo.Columns(cols...) }

func (e *entity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *entity) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 3)
	e.fieldMap["id"] = e.ID
	e.fieldMap["active"] = e.Active
	e.fieldMap["group_id"] = e.GroupID
}

func (e entity) clone(db *gorm.DB) entity {
	e.entityDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e entity) replaceDB(db *gorm.DB) entity {
	e.entityDo.ReplaceDB(db)
	return e
}

type entityDo struct{ gen.DO }

func (e entityDo) Debug() *entityDo {
	return e.withDO(e.DO.Debug())
}

func (e entityDo) WithContext(ctx context.Context) *entityDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e entityDo) ReadDB() *entityDo {
	return e.Clauses(dbresolver.Read)
}

func (e entityDo) WriteDB() *entityDo {
	return e.Clauses(dbresolver.Write)
}

func (e entityDo) Session(config *gorm.Session) *entityDo {
	return e.withDO(e.DO.Session(config))
}

func (e entityDo) Clauses(conds ...clause.Expression) *entityDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e entityDo) Returning(value interface{}, columns ...string) *entityDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e entityDo) Not(conds ...gen.Condition) *entityDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e entityDo) Or(conds ...gen.Condition) *entityDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e entityDo) Select(conds ...field.Expr) *entityDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e entityDo) Where(conds ...gen.Condition) *entityDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e entityDo) Order(conds ...field.Expr) *entityDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e entityDo) Distinct(cols ...field.Expr) *entityDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e entityDo) Omit(cols ...field.Expr) *entityDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e entityDo) Join(table schema.Tabler, on ...field.Expr) *entityDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e entityDo) LeftJoin(table schema.Tabler, on ...field.Expr) *entityDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e entityDo) RightJoin(table schema.Tabler, on ...field.Expr) *entityDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e entityDo) Group(cols ...field.Expr) *entityDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e entityDo) Having(conds ...gen.Condition) *entityDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e entityDo) Limit(limit int) *entityDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e entityDo) Offset(offset int) *entityDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e entityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *entityDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e entityDo) Unscoped() *entityDo {
	return e.withDO(e.DO.Unscoped())
}

func (e entityDo) Create(values ...*model.Entity) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e entityDo) CreateInBatches(values []*model.Entity, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e entityDo) Save(values ...*model.Entity) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e entityDo) First() (*model.Entity, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Entity), nil
	}
}

func (e entityDo) Take() (*model.Entity, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Entity), nil
	}
}

func (e entityDo) Last() (*model.Entity, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Entity), nil
	}
}

func (e entityDo) Find() ([]*model.Entity, error) {
	result, err := e.DO.Find()
	return result.([]*model.Entity), err
}

func (e entityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Entity, err error) {
	buf := make([]*model.Entity, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e entityDo) FindInBatches(result *[]*model.Entity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e entityDo) Attrs(attrs ...field.AssignExpr) *entityDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e entityDo) Assign(attrs ...field.AssignExpr) *entityDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e entityDo) Joins(fields ...field.RelationField) *entityDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e entityDo) Preload(fields ...field.RelationField) *entityDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e entityDo) FirstOrInit() (*model.Entity, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Entity), nil
	}
}

func (e entityDo) FirstOrCreate() (*model.Entity, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Entity), nil
	}
}

func (e entityDo) FindByPage(offset int, limit int) (result []*model.Entity, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e entityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e entityDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e entityDo) Delete(models ...*model.Entity) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *entityDo) withDO(do gen.Dao) *entityDo {
	e.DO = *do.(*gen.DO)
	return e
}
