// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vivianlazaras/storyteller/model"
)

func newExifTag(db *gorm.DB, opts ...gen.DOOption) exifTag {
	_exifTag := exifTag{}

	_exifTag.exifTagDo.UseDB(db, opts...)
	_exifTag.exifTagDo.UseModel(&model.ExifTag{})

	tableName := _exifTag.exifTagDo.TableName()
	_exifTag.ALL = field.NewAsterisk(tableName)
	_exifTag.ID = field.NewField(tableName, "id")
	_exifTag.Image = field.NewField(tableName, "image")
	_exifTag.Tag = field.NewInt32(tableName, "tag")
	_exifTag.Value = field.NewString(tableName, "value")

	_exifTag.fillFieldMap()

	return _exifTag
}

type exifTag struct {
	exifTagDo exifTagDo

	ALL   field.Asterisk
	ID    field.Field
	Image field.Field
	Tag   field.Int32
	Value field.String

	fieldMap map[string]field.Expr
}

func (e exifTag) Table(newTableName string) *exifTag {
	e.exifTagDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e exifTag) As(alias string) *exifTag {
	e.exifTagDo.DO = *(e.exifTagDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *exifTag) updateTableName(table string) *exifTag {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewField(table, "id")
	e.Image = field.NewField(table, "image")
	e.Tag = field.NewInt32(table, "tag")
	e.Value = field.NewString(table, "value")

	e.fillFieldMap()

	return e
}

func (e *exifTag) WithContext(ctx context.Context) *exifTagDo { return e.exifTagDo.WithContext(ctx) }

func (e exifTag) TableName() string { return e.exifTagDo.TableName() }

func (e exifTag) Alias() string { return e.exifTagDo.Alias() }

func (e exifTag) Columns(cols ...field.Expr) gen.Columns { return e.exifTagDo.Columns(cols...) }

func (e *exifTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *exifTag) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 4)
	e.fieldMap["id"] = e.ID
	e.fieldMap["image"] = e.Image
	e.fieldMap["tag"] = e.Tag
	e.fieldMap["value"] = e.Value
}

func (e exifTag) clone(db *gorm.DB) exifTag {
	e.exifTagDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e exifTag) replaceDB(db *gorm.DB) exifTag {
	e.exifTagDo.ReplaceDB(db)
	return e
}

type exifTagDo struct{ gen.DO }

func (e exifTagDo) Debug() *exifTagDo {
	return e.withDO(e.DO.Debug())
}

func (e exifTagDo) WithContext(ctx context.Context) *exifTagDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e exifTagDo) ReadDB() *exifTagDo {
	return e.Clauses(dbresolver.Read)
}

func (e exifTagDo) WriteDB() *exifTagDo {
	return e.Clauses(dbresolver.Write)
}

func (e exifTagDo) Session(config *gorm.Session) *exifTagDo {
	return e.withDO(e.DO.Session(config))
}

func (e exifTagDo) Clauses(conds ...clause.Expression) *exifTagDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e exifTagDo) Returning(value interface{}, columns ...string) *exifTagDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e exifTagDo) Not(conds ...gen.Condition) *exifTagDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e exifTagDo) Or(conds ...gen.Condition) *exifTagDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e exifTagDo) Select(conds ...field.Expr) *exifTagDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e exifTagDo) Where(conds ...gen.Condition) *exifTagDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e exifTagDo) Order(conds ...field.Expr) *exifTagDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e exifTagDo) Distinct(cols ...field.Expr) *exifTagDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e exifTagDo) Omit(cols ...field.Expr) *exifTagDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e exifTagDo) Join(table schema.Tabler, on ...field.Expr) *exifTagDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e exifTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) *exifTagDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e exifTagDo) RightJoin(table schema.Tabler, on ...field.Expr) *exifTagDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e exifTagDo) Group(cols ...field.Expr) *exifTagDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e exifTagDo) Having(conds ...gen.Condition) *exifTagDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e exifTagDo) Limit(limit int) *exifTagDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e exifTagDo) Offset(offset int) *exifTagDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e exifTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *exifTagDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e exifTagDo) Unscoped() *exifTagDo {
	return e.withDO(e.DO.Unscoped())
}

func (e exifTagDo) Create(values ...*model.ExifTag) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e exifTagDo) CreateInBatches(values []*model.ExifTag, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e exifTagDo) Save(values ...*model.ExifTag) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e exifTagDo) First() (*model.ExifTag, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExifTag), nil
	}
}

func (e exifTagDo) Take() (*model.ExifTag, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExifTag), nil
	}
}

func (e exifTagDo) Last() (*model.ExifTag, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExifTag), nil
	}
}

func (e exifTagDo) Find() ([]*model.ExifTag, error) {
	result, err := e.DO.Find()
	return result.([]*model.ExifTag), err
}

func (e exifTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ExifTag, err error) {
	buf := make([]*model.ExifTag, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e exifTagDo) FindInBatches(result *[]*model.ExifTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e exifTagDo) Attrs(attrs ...field.AssignExpr) *exifTagDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e exifTagDo) Assign(attrs ...field.AssignExpr) *exifTagDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e exifTagDo) Joins(fields ...field.RelationField) *exifTagDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e exifTagDo) Preload(fields ...field.RelationField) *exifTagDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e exifTagDo) FirstOrInit() (*model.ExifTag, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExifTag), nil
	}
}

func (e exifTagDo) FirstOrCreate() (*model.ExifTag, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExifTag), nil
	}
}

func (e exifTagDo) FindByPage(offset int, limit int) (result []*model.ExifTag, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e exifTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e exifTagDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e exifTagDo) Delete(models ...*model.ExifTag) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *exifTagDo) withDO(do gen.Dao) *exifTagDo {
	e.DO = *do.(*gen.DO)
	return e
}
