// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vivianlazaras/storyteller/model"
)

func newFragment(db *gorm.DB, opts ...gen.DOOption) fragment {
	_fragment := fragment{}

	_fragment.fragmentDo.UseDB(db, opts...)
	_fragment.fragmentDo.UseModel(&model.Fragment{})

	tableName := _fragment.fragmentDo.TableName()
	_fragment.ALL = field.NewAsterisk(tableName)
	_fragment.ID = field.NewField(tableName, "id")
	_fragment.Metadata = field.NewField(tableName, "metadata")
	_fragment.Idx = field.NewInt32(tableName, "idx")
	_fragment.Content = field.NewString(tableName, "content")
	_fragment.Name = field.NewString(tableName, "name")
	_fragment.LastEdited = field.NewInt64(tableName, "last_edited")
	_fragment.Created = field.NewInt64(tableName, "created")
	_fragment.Description = field.NewString(tableName, "description")

	_fragment.fillFieldMap()

	return _fragment
}

type fragment struct {
	fragmentDo fragmentDo

	ALL         field.Asterisk
	ID          field.Field
	Metadata    field.Field
	Idx         field.Int32
	Content     field.String
	Name        field.String
	LastEdited  field.Int64
	Created     field.Int64
	Description field.String

	fieldMap map[string]field.Expr
}

func (f fragment) Table(newTableName string) *fragment {
	f.fragmentDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fragment) As(alias string) *fragment {
	f.fragmentDo.DO = *(f.fragmentDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fragment) updateTableName(table string) *fragment {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewField(table, "id")
	f.Metadata = field.NewField(table, "metadata")
	f.Idx = field.NewInt32(table, "idx")
	f.Content = field.NewString(table, "content")
	f.Name = field.NewString(table, "name")
	f.LastEdited = field.NewInt64(table, "last_edited")
	f.Created = field.NewInt64(table, "created")
	f.Description = field.NewString(table, "description")

	f.fillFieldMap()

	return f
}

func (f *fragment) WithContext(ctx context.Context) *fragmentDo { return f.fragmentDo.WithContext(ctx) }

func (f fragment) TableName() string { return f.fragmentDo.TableName() }

func (f fragment) Alias() string { return f.fragmentDo.Alias() }

func (f fragment) Columns(cols ...field.Expr) gen.Columns { return f.fragmentDo.Columns(cols...) }

func (f *fragment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fragment) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 8)
	f.fieldMap["id"] = f.ID
	f.fieldMap["metadata"] = f.Metadata
	f.fieldMap["idx"] = f.Idx
	f.fieldMap["content"] = f.Content
	f.fieldMap["name"] = f.Name
	f.fieldMap["last_edited"] = f.LastEdited
	f.fieldMap["created"] = f.Created
	f.fieldMap["description"] = f.Description
}

func (f fragment) clone(db *gorm.DB) fragment {
	f.fragmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fragment) replaceDB(db *gorm.DB) fragment {
	f.fragmentDo.ReplaceDB(db)
	return f
}

type fragmentDo struct{ gen.DO }

func (f fragmentDo) Debug() *fragmentDo {
	return f.withDO(f.DO.Debug())
}

func (f fragmentDo) WithContext(ctx context.Context) *fragmentDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fragmentDo) ReadDB() *fragmentDo {
	return f.Clauses(dbresolver.Read)
}

func (f fragmentDo) WriteDB() *fragmentDo {
	return f.Clauses(dbresolver.Write)
}

func (f fragmentDo) Session(config *gorm.Session) *fragmentDo {
	return f.withDO(f.DO.Session(config))
}

func (f fragmentDo) Clauses(conds ...clause.Expression) *fragmentDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fragmentDo) Returning(value interface{}, columns ...string) *fragmentDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fragmentDo) Not(conds ...gen.Condition) *fragmentDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fragmentDo) Or(conds ...gen.Condition) *fragmentDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fragmentDo) Select(conds ...field.Expr) *fragmentDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fragmentDo) Where(conds ...gen.Condition) *fragmentDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fragmentDo) Order(conds ...field.Expr) *fragmentDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fragmentDo) Distinct(cols ...field.Expr) *fragmentDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fragmentDo) Omit(cols ...field.Expr) *fragmentDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fragmentDo) Join(table schema.Tabler, on ...field.Expr) *fragmentDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fragmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *fragmentDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fragmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *fragmentDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fragmentDo) Group(cols ...field.Expr) *fragmentDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fragmentDo) Having(conds ...gen.Condition) *fragmentDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fragmentDo) Limit(limit int) *fragmentDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fragmentDo) Offset(offset int) *fragmentDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fragmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *fragmentDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fragmentDo) Unscoped() *fragmentDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fragmentDo) Create(values ...*model.Fragment) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fragmentDo) CreateInBatches(values []*model.Fragment, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fragmentDo) Save(values ...*model.Fragment) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fragmentDo) First() (*model.Fragment, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Fragment), nil
	}
}

func (f fragmentDo) Take() (*model.Fragment, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Fragment), nil
	}
}

func (f fragmentDo) Last() (*model.Fragment, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Fragment), nil
	}
}

func (f fragmentDo) Find() ([]*model.Fragment, error) {
	result, err := f.DO.Find()
	return result.([]*model.Fragment), err
}

func (f fragmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Fragment, err error) {
	buf := make([]*model.Fragment, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fragmentDo) FindInBatches(result *[]*model.Fragment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fragmentDo) Attrs(attrs ...field.AssignExpr) *fragmentDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fragmentDo) Assign(attrs ...field.AssignExpr) *fragmentDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fragmentDo) Joins(fields ...field.RelationField) *fragmentDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fragmentDo) Preload(fields ...field.RelationField) *fragmentDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fragmentDo) FirstOrInit() (*model.Fragment, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Fragment), nil
	}
}

func (f fragmentDo) FirstOrCreate() (*model.Fragment, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Fragment), nil
	}
}

func (f fragmentDo) FindByPage(offset int, limit int) (result []*model.Fragment, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fragmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fragmentDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fragmentDo) Delete(models ...*model.Fragment) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fragmentDo) withDO(do gen.Dao) *fragmentDo {
	f.DO = *do.(*gen.DO)
	return f
}
