// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		Character:    newCharacter(db, opts...),
		Characterrel: newCharacterrel(db, opts...),
		Dataset:      newDataset(db, opts...),
		Edit:         newEdit(db, opts...),
		Entity:       newEntity(db, opts...),
		ExifTag:      newExifTag(db, opts...),
		Fragment:     newFragment(db, opts...),
		Graph:        newGraph(db, opts...),
		Group:        newGroup(db, opts...),
		Grouprel:     newGrouprel(db, opts...),
		Image:        newImage(db, opts...),
		License:      newLicense(db, opts...),
		Location:     newLocation(db, opts...),
		Metadatum:    newMetadatum(db, opts...),
		Moment:       newMoment(db, opts...),
		Note:         newNote(db, opts...),
		Recording:    newRecording(db, opts...),
		Relation:     newRelation(db, opts...),
		Story:        newStory(db, opts...),
		Tag:          newTag(db, opts...),
		Timeline:     newTimeline(db, opts...),
		Universe:     newUniverse(db, opts...),
		User:         newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Character    character
	Characterrel characterrel
	Dataset      dataset
	Edit         edit
	Entity       entity
	ExifTag      exifTag
	Fragment     fragment
	Graph        graph
	Group        group
	Grouprel     grouprel
	Image        image
	License      license
	Location     location
	Metadatum    metadatum
	Moment       moment
	Note         note
	Recording    recording
	Relation     relation
	Story        story
	Tag          tag
	Timeline     timeline
	Universe     universe
	User         user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Character:    q.Character.clone(db),
		Characterrel: q.Characterrel.clone(db),
		Dataset:      q.Dataset.clone(db),
		Edit:         q.Edit.clone(db),
		Entity:       q.Entity.clone(db),
		ExifTag:      q.ExifTag.clone(db),
		Fragment:     q.Fragment.clone(db),
		Graph:        q.Graph.clone(db),
		Group:        q.Group.clone(db),
		Grouprel:     q.Grouprel.clone(db),
		Image:        q.Image.clone(db),
		License:      q.License.clone(db),
		Location:     q.Location.clone(db),
		Metadatum:    q.Metadatum.clone(db),
		Moment:       q.Moment.clone(db),
		Note:         q.Note.clone(db),
		Recording:    q.Recording.clone(db),
		Relation:     q.Relation.clone(db),
		Story:        q.Story.clone(db),
		Tag:          q.Tag.clone(db),
		Timeline:     q.Timeline.clone(db),
		Universe:     q.Universe.clone(db),
		User:         q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Character:    q.Character.replaceDB(db),
		Characterrel: q.Characterrel.replaceDB(db),
		Dataset:      q.Dataset.replaceDB(db),
		Edit:         q.Edit.replaceDB(db),
		Entity:       q.Entity.replaceDB(db),
		ExifTag:      q.ExifTag.replaceDB(db),
		Fragment:     q.Fragment.replaceDB(db),
		Graph:        q.Graph.replaceDB(db),
		Group:        q.Group.replaceDB(db),
		Grouprel:     q.Grouprel.replaceDB(db),
		Image:        q.Image.replaceDB(db),
		License:      q.License.replaceDB(db),
		Location:     q.Location.replaceDB(db),
		Metadatum:    q.Metadatum.replaceDB(db),
		Moment:       q.Moment.replaceDB(db),
		Note:         q.Note.replaceDB(db),
		Recording:    q.Recording.replaceDB(db),
		Relation:     q.Relation.replaceDB(db),
		Story:        q.Story.replaceDB(db),
		Tag:          q.Tag.replaceDB(db),
		Timeline:     q.Timeline.replaceDB(db),
		Universe:     q.Universe.replaceDB(db),
		User:         q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Character    *characterDo
	Characterrel *characterrelDo
	Dataset      *datasetDo
	Edit         *editDo
	Entity       *entityDo
	ExifTag      *exifTagDo
	Fragment     *fragmentDo
	Graph        *graphDo
	Group        *groupDo
	Grouprel     *grouprelDo
	Image        *imageDo
	License      *licenseDo
	Location     *locationDo
	Metadatum    *metadatumDo
	Moment       *momentDo
	Note         *noteDo
	Recording    *recordingDo
	Relation     *relationDo
	Story        *storyDo
	Tag          *tagDo
	Timeline     *timelineDo
	Universe     *universeDo
	User         *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Character:    q.Character.WithContext(ctx),
		Characterrel: q.Characterrel.WithContext(ctx),
		Dataset:      q.Dataset.WithContext(ctx),
		Edit:         q.Edit.WithContext(ctx),
		Entity:       q.Entity.WithContext(ctx),
		ExifTag:      q.ExifTag.WithContext(ctx),
		Fragment:     q.Fragment.WithContext(ctx),
		Graph:        q.Graph.WithContext(ctx),
		Group:        q.Group.WithContext(ctx),
		Grouprel:     q.Grouprel.WithContext(ctx),
		Image:        q.Image.WithContext(ctx),
		License:      q.License.WithContext(ctx),
		Location:     q.Location.WithContext(ctx),
		Metadatum:    q.Metadatum.WithContext(ctx),
		Moment:       q.Moment.WithContext(ctx),
		Note:         q.Note.WithContext(ctx),
		Recording:    q.Recording.WithContext(ctx),
		Relation:     q.Relation.WithContext(ctx),
		Story:        q.Story.WithContext(ctx),
		Tag:          q.Tag.WithContext(ctx),
		Timeline:     q.Timeline.WithContext(ctx),
		Universe:     q.Universe.WithContext(ctx),
		User:         q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
