// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vivianlazaras/storyteller/model"
)

func newGraph(db *gorm.DB, opts ...gen.DOOption) graph {
	_graph := graph{}

	_graph.graphDo.UseDB(db, opts...)
	_graph.graphDo.UseModel(&model.Graph{})

	tableName := _graph.graphDo.TableName()
	_graph.ALL = field.NewAsterisk(tableName)
	_graph.ID = field.NewField(tableName, "id")
	_graph.Entity = field.NewField(tableName, "entity")
	_graph.Rendered = field.NewInt64(tableName, "rendered")
	_graph.DotData = field.NewString(tableName, "dot_data")
	_graph.Created = field.NewInt64(tableName, "created")

	_graph.fillFieldMap()

	return _graph
}

type graph struct {
	graphDo graphDo

	ALL      field.Asterisk
	ID       field.Field
	Entity   field.Field
	Rendered field.Int64
	DotData  field.String
	Created  field.Int64

	fieldMap map[string]field.Expr
}

func (g graph) Table(newTableName string) *graph {
	g.graphDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g graph) As(alias string) *graph {
	g.graphDo.DO = *(g.graphDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *graph) updateTableName(table string) *graph {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewField(table, "id")
	g.Entity = field.NewField(table, "entity")
	g.Rendered = field.NewInt64(table, "rendered")
	g.DotData = field.NewString(table, "dot_data")
	g.Created = field.NewInt64(table, "created")

	g.fillFieldMap()

	return g
}

func (g *graph) WithContext(ctx context.Context) *graphDo { return g.graphDo.WithContext(ctx) }

func (g graph) TableName() string { return g.graphDo.TableName() }

func (g graph) Alias() string { return g.graphDo.Alias() }

func (g graph) Columns(cols ...field.Expr) gen.Columns { return g.graphDo.Columns(cols...) }

func (g *graph) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *graph) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 5)
	g.fieldMap["id"] = g.ID
	g.fieldMap["entity"] = g.Entity
	g.fieldMap["rendered"] = g.Rendered
	g.fieldMap["dot_data"] = g.DotData
	g.fieldMap["created"] = g.Created
}

func (g graph) clone(db *gorm.DB) graph {
	g.graphDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g graph) replaceDB(db *gorm.DB) graph {
	g.graphDo.ReplaceDB(db)
	return g
}

type graphDo struct{ gen.DO }

func (g graphDo) Debug() *graphDo {
	return g.withDO(g.DO.Debug())
}

func (g graphDo) WithContext(ctx context.Context) *graphDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g graphDo) ReadDB() *graphDo {
	return g.Clauses(dbresolver.Read)
}

func (g graphDo) WriteDB() *graphDo {
	return g.Clauses(dbresolver.Write)
}

func (g graphDo) Session(config *gorm.Session) *graphDo {
	return g.withDO(g.DO.Session(config))
}

func (g graphDo) Clauses(conds ...clause.Expression) *graphDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g graphDo) Returning(value interface{}, columns ...string) *graphDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g graphDo) Not(conds ...gen.Condition) *graphDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g graphDo) Or(conds ...gen.Condition) *graphDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g graphDo) Select(conds ...field.Expr) *graphDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g graphDo) Where(conds ...gen.Condition) *graphDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g graphDo) Order(conds ...field.Expr) *graphDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g graphDo) Distinct(cols ...field.Expr) *graphDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g graphDo) Omit(cols ...field.Expr) *graphDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g graphDo) Join(table schema.Tabler, on ...field.Expr) *graphDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g graphDo) LeftJoin(table schema.Tabler, on ...field.Expr) *graphDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g graphDo) RightJoin(table schema.Tabler, on ...field.Expr) *graphDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g graphDo) Group(cols ...field.Expr) *graphDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g graphDo) Having(conds ...gen.Condition) *graphDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g graphDo) Limit(limit int) *graphDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g graphDo) Offset(offset int) *graphDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g graphDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *graphDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g graphDo) Unscoped() *graphDo {
	return g.withDO(g.DO.Unscoped())
}

func (g graphDo) Create(values ...*model.Graph) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g graphDo) CreateInBatches(values []*model.Graph, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g graphDo) Save(values ...*model.Graph) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g graphDo) First() (*model.Graph, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Graph), nil
	}
}

func (g graphDo) Take() (*model.Graph, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Graph), nil
	}
}

func (g graphDo) Last() (*model.Graph, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Graph), nil
	}
}

func (g graphDo) Find() ([]*model.Graph, error) {
	result, err := g.DO.Find()
	return result.([]*model.Graph), err
}

func (g graphDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Graph, err error) {
	buf := make([]*model.Graph, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g graphDo) FindInBatches(result *[]*model.Graph, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g graphDo) Attrs(attrs ...field.AssignExpr) *graphDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g graphDo) Assign(attrs ...field.AssignExpr) *graphDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g graphDo) Joins(fields ...field.RelationField) *graphDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g graphDo) Preload(fields ...field.RelationField) *graphDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g graphDo) FirstOrInit() (*model.Graph, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Graph), nil
	}
}

func (g graphDo) FirstOrCreate() (*model.Graph, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Graph), nil
	}
}

func (g graphDo) FindByPage(offset int, limit int) (result []*model.Graph, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g graphDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g graphDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g graphDo) Delete(models ...*model.Graph) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *graphDo) withDO(do gen.Dao) *graphDo {
	g.DO = *do.(*gen.DO)
	return g
}
