// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vivianlazaras/storyteller/model"
)

func newGrouprel(db *gorm.DB, opts ...gen.DOOption) grouprel {
	_grouprel := grouprel{}

	_grouprel.grouprelDo.UseDB(db, opts...)
	_grouprel.grouprelDo.UseModel(&model.Grouprel{})

	tableName := _grouprel.grouprelDo.TableName()
	_grouprel.ALL = field.NewAsterisk(tableName)
	_grouprel.ID = field.NewField(tableName, "id")
	_grouprel.GroupID = field.NewField(tableName, "group_id")
	_grouprel.UserID = field.NewField(tableName, "user_id")
	_grouprel.Description = field.NewString(tableName, "description")

	_grouprel.fillFieldMap()

	return _grouprel
}

type grouprel struct {
	grouprelDo grouprelDo

	ALL         field.Asterisk
	ID          field.Field
	GroupID     field.Field
	UserID      field.Field
	Description field.String

	fieldMap map[string]field.Expr
}

func (g grouprel) Table(newTableName string) *grouprel {
	g.grouprelDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g grouprel) As(alias string) *grouprel {
	g.grouprelDo.DO = *(g.grouprelDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *grouprel) updateTableName(table string) *grouprel {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewField(table, "id")
	g.GroupID = field.NewField(table, "group_id")
	g.UserID = field.NewField(table, "user_id")
	g.Description = field.NewString(table, "description")

	g.fillFieldMap()

	return g
}

func (g *grouprel) WithContext(ctx context.Context) *grouprelDo { return g.grouprelDo.WithContext(ctx) }

func (g grouprel) TableName() string { return g.grouprelDo.TableName() }

func (g grouprel) Alias() string { return g.grouprelDo.Alias() }

func (g grouprel) Columns(cols ...field.Expr) gen.Columns { return g.grouprelDo.Columns(cols...) }

func (g *grouprel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *grouprel) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 4)
	g.fieldMap["id"] = g.ID
	g.fieldMap["group_id"] = g.GroupID
	g.fieldMap["user_id"] = g.UserID
	g.fieldMap["description"] = g.Description
}

func (g grouprel) clone(db *gorm.DB) grouprel {
	g.grouprelDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g grouprel) replaceDB(db *gorm.DB) grouprel {
	g.grouprelDo.ReplaceDB(db)
	return g
}

type grouprelDo struct{ gen.DO }

func (g grouprelDo) Debug() *grouprelDo {
	return g.withDO(g.DO.Debug())
}

func (g grouprelDo) WithContext(ctx context.Context) *grouprelDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g grouprelDo) ReadDB() *grouprelDo {
	return g.Clauses(dbresolver.Read)
}

func (g grouprelDo) WriteDB() *grouprelDo {
	return g.Clauses(dbresolver.Write)
}

func (g grouprelDo) Session(config *gorm.Session) *grouprelDo {
	return g.withDO(g.DO.Session(config))
}

func (g grouprelDo) Clauses(conds ...clause.Expression) *grouprelDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g grouprelDo) Returning(value interface{}, columns ...string) *grouprelDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g grouprelDo) Not(conds ...gen.Condition) *grouprelDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g grouprelDo) Or(conds ...gen.Condition) *grouprelDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g grouprelDo) Select(conds ...field.Expr) *grouprelDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g grouprelDo) Where(conds ...gen.Condition) *grouprelDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g grouprelDo) Order(conds ...field.Expr) *grouprelDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g grouprelDo) Distinct(cols ...field.Expr) *grouprelDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g grouprelDo) Omit(cols ...field.Expr) *grouprelDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g grouprelDo) Join(table schema.Tabler, on ...field.Expr) *grouprelDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g grouprelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *grouprelDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g grouprelDo) RightJoin(table schema.Tabler, on ...field.Expr) *grouprelDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g grouprelDo) Group(cols ...field.Expr) *grouprelDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g grouprelDo) Having(conds ...gen.Condition) *grouprelDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g grouprelDo) Limit(limit int) *grouprelDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g grouprelDo) Offset(offset int) *grouprelDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g grouprelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *grouprelDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g grouprelDo) Unscoped() *grouprelDo {
	return g.withDO(g.DO.Unscoped())
}

func (g grouprelDo) Create(values ...*model.Grouprel) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g grouprelDo) CreateInBatches(values []*model.Grouprel, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g grouprelDo) Save(values ...*model.Grouprel) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g grouprelDo) First() (*model.Grouprel, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Grouprel), nil
	}
}

func (g grouprelDo) Take() (*model.Grouprel, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Grouprel), nil
	}
}

func (g grouprelDo) Last() (*model.Grouprel, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Grouprel), nil
	}
}

func (g grouprelDo) Find() ([]*model.Grouprel, error) {
	result, err := g.DO.Find()
	return result.([]*model.Grouprel), err
}

func (g grouprelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Grouprel, err error) {
	buf := make([]*model.Grouprel, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g grouprelDo) FindInBatches(result *[]*model.Grouprel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g grouprelDo) Attrs(attrs ...field.AssignExpr) *grouprelDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g grouprelDo) Assign(attrs ...field.AssignExpr) *grouprelDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g grouprelDo) Joins(fields ...field.RelationField) *grouprelDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g grouprelDo) Preload(fields ...field.RelationField) *grouprelDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g grouprelDo) FirstOrInit() (*model.Grouprel, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Grouprel), nil
	}
}

func (g grouprelDo) FirstOrCreate() (*model.Grouprel, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Grouprel), nil
	}
}

func (g grouprelDo) FindByPage(offset int, limit int) (result []*model.Grouprel, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g grouprelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g grouprelDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g grouprelDo) Delete(models ...*model.Grouprel) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *grouprelDo) withDO(do gen.Dao) *grouprelDo {
	g.DO = *do.(*gen.DO)
	return g
}
