// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vivianlazaras/storyteller/model"
)

func newLicense(db *gorm.DB, opts ...gen.DOOption) license {
	_license := license{}

	_license.licenseDo.UseDB(db, opts...)
	_license.licenseDo.UseModel(&model.License{})

	tableName := _license.licenseDo.TableName()
	_license.ALL = field.NewAsterisk(tableName)
	_license.ID = field.NewField(tableName, "id")
	_license.Name = field.NewString(tableName, "name")
	_license.Description = field.NewString(tableName, "description")
	_license.Public = field.NewBool(tableName, "public")
	_license.Content = field.NewString(tableName, "content")

	_license.fillFieldMap()

	return _license
}

type license struct {
	licenseDo licenseDo

	ALL         field.Asterisk
	ID          field.Field
	Name        field.String
	Description field.String
	Public      field.Bool
	Content     field.String

	fieldMap map[string]field.Expr
}

func (l license) Table(newTableName string) *license {
	l.licenseDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l license) As(alias string) *license {
	l.licenseDo.DO = *(l.licenseDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *license) updateTableName(table string) *license {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewField(table, "id")
	l.Name = field.NewString(table, "name")
	l.Description = field.NewString(table, "description")
	l.Public = field.NewBool(table, "public")
	l.Content = field.NewString(table, "content")

	l.fillFieldMap()

	return l
}

func (l *license) WithContext(ctx context.Context) *licenseDo { return l.licenseDo.WithContext(ctx) }

func (l license) TableName() string { return l.licenseDo.TableName() }

func (l license) Alias() string { return l.licenseDo.Alias() }

func (l license) Columns(cols ...field.Expr) gen.Columns { return l.licenseDo.Columns(cols...) }

func (l *license) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *license) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 5)
	l.fieldMap["id"] = l.ID
	l.fieldMap["name"] = l.Name
	l.fieldMap["description"] = l.Description
	l.fieldMap["public"] = l.Public
	l.fieldMap["content"] = l.Content
}

func (l license) clone(db *gorm.DB) license {
	l.licenseDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l license) replaceDB(db *gorm.DB) license {
	l.licenseDo.ReplaceDB(db)
	return l
}

type licenseDo struct{ gen.DO }

func (l licenseDo) Debug() *licenseDo {
	return l.withDO(l.DO.Debug())
}

func (l licenseDo) WithContext(ctx context.Context) *licenseDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l licenseDo) ReadDB() *licenseDo {
	return l.Clauses(dbresolver.Read)
}

func (l licenseDo) WriteDB() *licenseDo {
	return l.Clauses(dbresolver.Write)
}

func (l licenseDo) Session(config *gorm.Session) *licenseDo {
	return l.withDO(l.DO.Session(config))
}

func (l licenseDo) Clauses(conds ...clause.Expression) *licenseDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l licenseDo) Returning(value interface{}, columns ...string) *licenseDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l licenseDo) Not(conds ...gen.Condition) *licenseDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l licenseDo) Or(conds ...gen.Condition) *licenseDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l licenseDo) Select(conds ...field.Expr) *licenseDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l licenseDo) Where(conds ...gen.Condition) *licenseDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l licenseDo) Order(conds ...field.Expr) *licenseDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l licenseDo) Distinct(cols ...field.Expr) *licenseDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l licenseDo) Omit(cols ...field.Expr) *licenseDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l licenseDo) Join(table schema.Tabler, on ...field.Expr) *licenseDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l licenseDo) LeftJoin(table schema.Tabler, on ...field.Expr) *licenseDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l licenseDo) RightJoin(table schema.Tabler, on ...field.Expr) *licenseDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l licenseDo) Group(cols ...field.Expr) *licenseDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l licenseDo) Having(conds ...gen.Condition) *licenseDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l licenseDo) Limit(limit int) *licenseDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l licenseDo) Offset(offset int) *licenseDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l licenseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *licenseDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l licenseDo) Unscoped() *licenseDo {
	return l.withDO(l.DO.Unscoped())
}

func (l licenseDo) Create(values ...*model.License) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l licenseDo) CreateInBatches(values []*model.License, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l licenseDo) Save(values ...*model.License) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l licenseDo) First() (*model.License, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.License), nil
	}
}

func (l licenseDo) Take() (*model.License, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.License), nil
	}
}

func (l licenseDo) Last() (*model.License, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.License), nil
	}
}

func (l licenseDo) Find() ([]*model.License, error) {
	result, err := l.DO.Find()
	return result.([]*model.License), err
}

func (l licenseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.License, err error) {
	buf := make([]*model.License, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l licenseDo) FindInBatches(result *[]*model.License, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l licenseDo) Attrs(attrs ...field.AssignExpr) *licenseDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l licenseDo) Assign(attrs ...field.AssignExpr) *licenseDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l licenseDo) Joins(fields ...field.RelationField) *licenseDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l licenseDo) Preload(fields ...field.RelationField) *licenseDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l licenseDo) FirstOrInit() (*model.License, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.License), nil
	}
}

func (l licenseDo) FirstOrCreate() (*model.License, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.License), nil
	}
}

func (l licenseDo) FindByPage(offset int, limit int) (result []*model.License, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l licenseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l licenseDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l licenseDo) Delete(models ...*model.License) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *licenseDo) withDO(do gen.Dao) *licenseDo {
	l.DO = *do.(*gen.DO)
	return l
}
