// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vivianlazaras/storyteller/model"
)

func newMetadatum(db *gorm.DB, opts ...gen.DOOption) metadatum {
	_metadatum := metadatum{}

	_metadatum.metadatumDo.UseDB(db, opts...)
	_metadatum.metadatumDo.UseModel(&model.Metadatum{})

	tableName := _metadatum.metadatumDo.TableName()
	_metadatum.ALL = field.NewAsterisk(tableName)
	_metadatum.ID = field.NewField(tableName, "id")
	_metadatum.Creator = field.NewField(tableName, "creator")
	_metadatum.License = field.NewField(tableName, "license")
	_metadatum.Public = field.NewBool(tableName, "public")
	_metadatum.Active = field.NewBool(tableName, "active")

	_metadatum.fillFieldMap()

	return _metadatum
}

type metadatum struct {
	metadatumDo metadatumDo

	ALL     field.Asterisk
	ID      field.Field
	Creator field.Field
	License field.Field
	Public  field.Bool
	Active  field.Bool

	fieldMap map[string]field.Expr
}

func (m metadatum) Table(newTableName string) *metadatum {
	m.metadatumDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m metadatum) As(alias string) *metadatum {
	m.metadatumDo.DO = *(m.metadatumDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *metadatum) updateTableName(table string) *metadatum {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewField(table, "id")
	m.Creator = field.NewField(table, "creator")
	m.License = field.NewField(table, "license")
	m.Public = field.NewBool(table, "public")
	m.Active = field.NewBool(table, "active")

	m.fillFieldMap()

	return m
}

func (m *metadatum) WithContext(ctx context.Context) *metadatumDo {
	return m.metadatumDo.WithContext(ctx)
}

func (m metadatum) TableName() string { return m.metadatumDo.TableName() }

func (m metadatum) Alias() string { return m.metadatumDo.Alias() }

func (m metadatum) Columns(cols ...field.Expr) gen.Columns { return m.metadatumDo.Columns(cols...) }

func (m *metadatum) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *metadatum) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 5)
	m.fieldMap["id"] = m.ID
	m.fieldMap["creator"] = m.Creator
	m.fieldMap["license"] = m.License
	m.fieldMap["public"] = m.Public
	m.fieldMap["active"] = m.Active
}

func (m metadatum) clone(db *gorm.DB) metadatum {
	m.metadatumDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m metadatum) replaceDB(db *gorm.DB) metadatum {
	m.metadatumDo.ReplaceDB(db)
	return m
}

type metadatumDo struct{ gen.DO }

func (m metadatumDo) Debug() *metadatumDo {
	return m.withDO(m.DO.Debug())
}

func (m metadatumDo) WithContext(ctx context.Context) *metadatumDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m metadatumDo) ReadDB() *metadatumDo {
	return m.Clauses(dbresolver.Read)
}

func (m metadatumDo) WriteDB() *metadatumDo {
	return m.Clauses(dbresolver.Write)
}

func (m metadatumDo) Session(config *gorm.Session) *metadatumDo {
	return m.withDO(m.DO.Session(config))
}

func (m metadatumDo) Clauses(conds ...clause.Expression) *metadatumDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m metadatumDo) Returning(value interface{}, columns ...string) *metadatumDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m metadatumDo) Not(conds ...gen.Condition) *metadatumDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m metadatumDo) Or(conds ...gen.Condition) *metadatumDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m metadatumDo) Select(conds ...field.Expr) *metadatumDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m metadatumDo) Where(conds ...gen.Condition) *metadatumDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m metadatumDo) Order(conds ...field.Expr) *metadatumDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m metadatumDo) Distinct(cols ...field.Expr) *metadatumDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m metadatumDo) Omit(cols ...field.Expr) *metadatumDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m metadatumDo) Join(table schema.Tabler, on ...field.Expr) *metadatumDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m metadatumDo) LeftJoin(table schema.Tabler, on ...field.Expr) *metadatumDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m metadatumDo) RightJoin(table schema.Tabler, on ...field.Expr) *metadatumDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m metadatumDo) Group(cols ...field.Expr) *metadatumDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m metadatumDo) Having(conds ...gen.Condition) *metadatumDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m metadatumDo) Limit(limit int) *metadatumDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m metadatumDo) Offset(offset int) *metadatumDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m metadatumDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *metadatumDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m metadatumDo) Unscoped() *metadatumDo {
	return m.withDO(m.DO.Unscoped())
}

func (m metadatumDo) Create(values ...*model.Metadatum) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m metadatumDo) CreateInBatches(values []*model.Metadatum, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m metadatumDo) Save(values ...*model.Metadatum) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m metadatumDo) First() (*model.Metadatum, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metadatum), nil
	}
}

func (m metadatumDo) Take() (*model.Metadatum, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metadatum), nil
	}
}

func (m metadatumDo) Last() (*model.Metadatum, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metadatum), nil
	}
}

func (m metadatumDo) Find() ([]*model.Metadatum, error) {
	result, err := m.DO.Find()
	return result.([]*model.Metadatum), err
}

func (m metadatumDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Metadatum, err error) {
	buf := make([]*model.Metadatum, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m metadatumDo) FindInBatches(result *[]*model.Metadatum, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m metadatumDo) Attrs(attrs ...field.AssignExpr) *metadatumDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m metadatumDo) Assign(attrs ...field.AssignExpr) *metadatumDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m metadatumDo) Joins(fields ...field.RelationField) *metadatumDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m metadatumDo) Preload(fields ...field.RelationField) *metadatumDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m metadatumDo) FirstOrInit() (*model.Metadatum, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metadatum), nil
	}
}

func (m metadatumDo) FirstOrCreate() (*model.Metadatum, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metadatum), nil
	}
}

func (m metadatumDo) FindByPage(offset int, limit int) (result []*model.Metadatum, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m metadatumDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m metadatumDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m metadatumDo) Delete(models ...*model.Metadatum) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *metadatumDo) withDO(do gen.Dao) *metadatumDo {
	m.DO = *do.(*gen.DO)
	return m
}
