// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vivianlazaras/storyteller/model"
)

func newRecording(db *gorm.DB, opts ...gen.DOOption) recording {
	_recording := recording{}

	_recording.recordingDo.UseDB(db, opts...)
	_recording.recordingDo.UseModel(&model.Recording{})

	tableName := _recording.recordingDo.TableName()
	_recording.ALL = field.NewAsterisk(tableName)
	_recording.ID = field.NewField(tableName, "id")
	_recording.Title = field.NewString(tableName, "title")
	_recording.Artist = field.NewString(tableName, "artist")
	_recording.Album = field.NewString(tableName, "album")
	_recording.Genre = field.NewString(tableName, "genre")
	_recording.Year = field.NewInt32(tableName, "year")
	_recording.TrackNumber = field.NewInt32(tableName, "track_number")
	_recording.DiscNumber = field.NewInt32(tableName, "disc_number")
	_recording.AlbumArtist = field.NewString(tableName, "album_artist")
	_recording.Comment = field.NewString(tableName, "comment")
	_recording.Composer = field.NewString(tableName, "composer")
	_recording.Lyrics = field.NewString(tableName, "lyrics")
	_recording.Created = field.NewInt64(tableName, "created")
	_recording.LastEditted = field.NewInt64(tableName, "last_editted")

	_recording.fillFieldMap()

	return _recording
}

type recording struct {
	recordingDo recordingDo

	ALL         field.Asterisk
	ID          field.Field
	Title       field.String
	Artist      field.String
	Album       field.String
	Genre       field.String
	Year        field.Int32
	TrackNumber field.Int32
	DiscNumber  field.Int32
	AlbumArtist field.String
	Comment     field.String
	Composer    field.String
	Lyrics      field.String
	Created     field.Int64
	LastEditted field.Int64

	fieldMap map[string]field.Expr
}

func (r recording) Table(newTableName string) *recording {
	r.recordingDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r recording) As(alias string) *recording {
	r.recordingDo.DO = *(r.recordingDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *recording) updateTableName(table string) *recording {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewField(table, "id")
	r.Title = field.NewString(table, "title")
	r.Artist = field.NewString(table, "artist")
	r.Album = field.NewString(table, "album")
	r.Genre = field.NewString(table, "genre")
	r.Year = field.NewInt32(table, "year")
	r.TrackNumber = field.NewInt32(table, "track_number")
	r.DiscNumber = field.NewInt32(table, "disc_number")
	r.AlbumArtist = field.NewString(table, "album_artist")
	r.Comment = field.NewString(table, "comment")
	r.Composer = field.NewString(table, "composer")
	r.Lyrics = field.NewString(table, "lyrics")
	r.Created = field.NewInt64(table, "created")
	r.LastEditted = field.NewInt64(table, "last_editted")

	r.fillFieldMap()

	return r
}

func (r *recording) WithContext(ctx context.Context) *recordingDo {
	return r.recordingDo.WithContext(ctx)
}

func (r recording) TableName() string { return r.recordingDo.TableName() }

func (r recording) Alias() string { return r.recordingDo.Alias() }

func (r recording) Columns(cols ...field.Expr) gen.Columns { return r.recordingDo.Columns(cols...) }

func (r *recording) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *recording) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 14)
	r.fieldMap["id"] = r.ID
	r.fieldMap["title"] = r.Title
	r.fieldMap["artist"] = r.Artist
	r.fieldMap["album"] = r.Album
	r.fieldMap["genre"] = r.Genre
	r.fieldMap["year"] = r.Year
	r.fieldMap["track_number"] = r.TrackNumber
	r.fieldMap["disc_number"] = r.DiscNumber
	r.fieldMap["album_artist"] = r.AlbumArtist
	r.fieldMap["comment"] = r.Comment
	r.fieldMap["composer"] = r.Composer
	r.fieldMap["lyrics"] = r.Lyrics
	r.fieldMap["created"] = r.Created
	r.fieldMap["last_editted"] = r.LastEditted
}

func (r recording) clone(db *gorm.DB) recording {
	r.recordingDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r recording) replaceDB(db *gorm.DB) recording {
	r.recordingDo.ReplaceDB(db)
	return r
}

type recordingDo struct{ gen.DO }

func (r recordingDo) Debug() *recordingDo {
	return r.withDO(r.DO.Debug())
}

func (r recordingDo) WithContext(ctx context.Context) *recordingDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r recordingDo) ReadDB() *recordingDo {
	return r.Clauses(dbresolver.Read)
}

func (r recordingDo) WriteDB() *recordingDo {
	return r.Clauses(dbresolver.Write)
}

func (r recordingDo) Session(config *gorm.Session) *recordingDo {
	return r.withDO(r.DO.Session(config))
}

func (r recordingDo) Clauses(conds ...clause.Expression) *recordingDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r recordingDo) Returning(value interface{}, columns ...string) *recordingDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r recordingDo) Not(conds ...gen.Condition) *recordingDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r recordingDo) Or(conds ...gen.Condition) *recordingDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r recordingDo) Select(conds ...field.Expr) *recordingDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r recordingDo) Where(conds ...gen.Condition) *recordingDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r recordingDo) Order(conds ...field.Expr) *recordingDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r recordingDo) Distinct(cols ...field.Expr) *recordingDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r recordingDo) Omit(cols ...field.Expr) *recordingDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r recordingDo) Join(table schema.Tabler, on ...field.Expr) *recordingDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r recordingDo) LeftJoin(table schema.Tabler, on ...field.Expr) *recordingDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r recordingDo) RightJoin(table schema.Tabler, on ...field.Expr) *recordingDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r recordingDo) Group(cols ...field.Expr) *recordingDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r recordingDo) Having(conds ...gen.Condition) *recordingDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r recordingDo) Limit(limit int) *recordingDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r recordingDo) Offset(offset int) *recordingDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r recordingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *recordingDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r recordingDo) Unscoped() *recordingDo {
	return r.withDO(r.DO.Unscoped())
}

func (r recordingDo) Create(values ...*model.Recording) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r recordingDo) CreateInBatches(values []*model.Recording, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r recordingDo) Save(values ...*model.Recording) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r recordingDo) First() (*model.Recording, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Recording), nil
	}
}

func (r recordingDo) Take() (*model.Recording, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Recording), nil
	}
}

func (r recordingDo) Last() (*model.Recording, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Recording), nil
	}
}

func (r recordingDo) Find() ([]*model.Recording, error) {
	result, err := r.DO.Find()
	return result.([]*model.Recording), err
}

func (r recordingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Recording, err error) {
	buf := make([]*model.Recording, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r recordingDo) FindInBatches(result *[]*model.Recording, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r recordingDo) Attrs(attrs ...field.AssignExpr) *recordingDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r recordingDo) Assign(attrs ...field.AssignExpr) *recordingDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r recordingDo) Joins(fields ...field.RelationField) *recordingDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r recordingDo) Preload(fields ...field.RelationField) *recordingDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r recordingDo) FirstOrInit() (*model.Recording, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Recording), nil
	}
}

func (r recordingDo) FirstOrCreate() (*model.Recording, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Recording), nil
	}
}

func (r recordingDo) FindByPage(offset int, limit int) (result []*model.Recording, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r recordingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r recordingDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r recordingDo) Delete(models ...*model.Recording) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *recordingDo) withDO(do gen.Dao) *recordingDo {
	r.DO = *do.(*gen.DO)
	return r
}
