// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vivianlazaras/storyteller/model"
)

func newStory(db *gorm.DB, opts ...gen.DOOption) story {
	_story := story{}

	_story.storyDo.UseDB(db, opts...)
	_story.storyDo.UseModel(&model.Story{})

	tableName := _story.storyDo.TableName()
	_story.ALL = field.NewAsterisk(tableName)
	_story.ID = field.NewField(tableName, "id")
	_story.Name = field.NewString(tableName, "name")
	_story.Description = field.NewString(tableName, "description")
	_story.Renderer = field.NewString(tableName, "renderer")
	_story.Metadata = field.NewField(tableName, "metadata")
	_story.Created = field.NewInt64(tableName, "created")
	_story.LastEdited = field.NewInt64(tableName, "last_edited")
	_story.Image = field.NewString(tableName, "image")

	_story.fillFieldMap()

	return _story
}

type story struct {
	storyDo storyDo

	ALL         field.Asterisk
	ID          field.Field
	Name        field.String
	Description field.String
	Renderer    field.String
	Metadata    field.Field
	Created     field.Int64
	LastEdited  field.Int64
	Image       field.String

	fieldMap map[string]field.Expr
}

func (s story) Table(newTableName string) *story {
	s.storyDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s story) As(alias string) *story {
	s.storyDo.DO = *(s.storyDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *story) updateTableName(table string) *story {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewField(table, "id")
	s.Name = field.NewString(table, "name")
	s.Description = field.NewString(table, "description")
	s.Renderer = field.NewString(table, "renderer")
	s.Metadata = field.NewField(table, "metadata")
	s.Created = field.NewInt64(table, "created")
	s.LastEdited = field.NewInt64(table, "last_edited")
	s.Image = field.NewString(table, "image")

	s.fillFieldMap()

	return s
}

func (s *story) WithContext(ctx context.Context) *storyDo { return s.storyDo.WithContext(ctx) }

func (s story) TableName() string { return s.storyDo.TableName() }

func (s story) Alias() string { return s.storyDo.Alias() }

func (s story) Columns(cols ...field.Expr) gen.Columns { return s.storyDo.Columns(cols...) }

func (s *story) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *story) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["description"] = s.Description
	s.fieldMap["renderer"] = s.Renderer
	s.fieldMap["metadata"] = s.Metadata
	s.fieldMap["created"] = s.Created
	s.fieldMap["last_edited"] = s.LastEdited
	s.fieldMap["image"] = s.Image
}

func (s story) clone(db *gorm.DB) story {
	s.storyDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s story) replaceDB(db *gorm.DB) story {
	s.storyDo.ReplaceDB(db)
	return s
}

type storyDo struct{ gen.DO }

func (s storyDo) Debug() *storyDo {
	return s.withDO(s.DO.Debug())
}

func (s storyDo) WithContext(ctx context.Context) *storyDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s storyDo) ReadDB() *storyDo {
	return s.Clauses(dbresolver.Read)
}

func (s storyDo) WriteDB() *storyDo {
	return s.Clauses(dbresolver.Write)
}

func (s storyDo) Session(config *gorm.Session) *storyDo {
	return s.withDO(s.DO.Session(config))
}

func (s storyDo) Clauses(conds ...clause.Expression) *storyDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s storyDo) Returning(value interface{}, columns ...string) *storyDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s storyDo) Not(conds ...gen.Condition) *storyDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s storyDo) Or(conds ...gen.Condition) *storyDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s storyDo) Select(conds ...field.Expr) *storyDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s storyDo) Where(conds ...gen.Condition) *storyDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s storyDo) Order(conds ...field.Expr) *storyDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s storyDo) Distinct(cols ...field.Expr) *storyDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s storyDo) Omit(cols ...field.Expr) *storyDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s storyDo) Join(table schema.Tabler, on ...field.Expr) *storyDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s storyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *storyDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s storyDo) RightJoin(table schema.Tabler, on ...field.Expr) *storyDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s storyDo) Group(cols ...field.Expr) *storyDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s storyDo) Having(conds ...gen.Condition) *storyDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s storyDo) Limit(limit int) *storyDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s storyDo) Offset(offset int) *storyDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s storyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *storyDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s storyDo) Unscoped() *storyDo {
	return s.withDO(s.DO.Unscoped())
}

func (s storyDo) Create(values ...*model.Story) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s storyDo) CreateInBatches(values []*model.Story, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s storyDo) Save(values ...*model.Story) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s storyDo) First() (*model.Story, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Story), nil
	}
}

func (s storyDo) Take() (*model.Story, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Story), nil
	}
}

func (s storyDo) Last() (*model.Story, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Story), nil
	}
}

func (s storyDo) Find() ([]*model.Story, error) {
	result, err := s.DO.Find()
	return result.([]*model.Story), err
}

func (s storyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Story, err error) {
	buf := make([]*model.Story, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s storyDo) FindInBatches(result *[]*model.Story, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s storyDo) Attrs(attrs ...field.AssignExpr) *storyDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s storyDo) Assign(attrs ...field.AssignExpr) *storyDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s storyDo) Joins(fields ...field.RelationField) *storyDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s storyDo) Preload(fields ...field.RelationField) *storyDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s storyDo) FirstOrInit() (*model.Story, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Story), nil
	}
}

func (s storyDo) FirstOrCreate() (*model.Story, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Story), nil
	}
}

func (s storyDo) FindByPage(offset int, limit int) (result []*model.Story, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s storyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s storyDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s storyDo) Delete(models ...*model.Story) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *storyDo) withDO(do gen.Dao) *storyDo {
	s.DO = *do.(*gen.DO)
	return s
}
