// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vivianlazaras/storyteller/model"
)

func newTimeline(db *gorm.DB, opts ...gen.DOOption) timeline {
	_timeline := timeline{}

	_timeline.timelineDo.UseDB(db, opts...)
	_timeline.timelineDo.UseModel(&model.Timeline{})

	tableName := _timeline.timelineDo.TableName()
	_timeline.ALL = field.NewAsterisk(tableName)
	_timeline.ID = field.NewField(tableName, "id")
	_timeline.Created = field.NewInt64(tableName, "created")
	_timeline.LastEdited = field.NewInt64(tableName, "last_edited")
	_timeline.Description = field.NewString(tableName, "description")
	_timeline.Name = field.NewString(tableName, "name")
	_timeline.Source = field.NewField(tableName, "source")

	_timeline.fillFieldMap()

	return _timeline
}

type timeline struct {
	timelineDo timelineDo

	ALL         field.Asterisk
	ID          field.Field
	Created     field.Int64
	LastEdited  field.Int64
	Description field.String
	Name        field.String
	Source      field.Field

	fieldMap map[string]field.Expr
}

func (t timeline) Table(newTableName string) *timeline {
	t.timelineDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t timeline) As(alias string) *timeline {
	t.timelineDo.DO = *(t.timelineDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *timeline) updateTableName(table string) *timeline {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewField(table, "id")
	t.Created = field.NewInt64(table, "created")
	t.LastEdited = field.NewInt64(table, "last_edited")
	t.Description = field.NewString(table, "description")
	t.Name = field.NewString(table, "name")
	t.Source = field.NewField(table, "source")

	t.fillFieldMap()

	return t
}

func (t *timeline) WithContext(ctx context.Context) *timelineDo { return t.timelineDo.WithContext(ctx) }

func (t timeline) TableName() string { return t.timelineDo.TableName() }

func (t timeline) Alias() string { return t.timelineDo.Alias() }

func (t timeline) Columns(cols ...field.Expr) gen.Columns { return t.timelineDo.Columns(cols...) }

func (t *timeline) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *timeline) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 6)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created"] = t.Created
	t.fieldMap["last_edited"] = t.LastEdited
	t.fieldMap["description"] = t.Description
	t.fieldMap["name"] = t.Name
	t.fieldMap["source"] = t.Source
}

func (t timeline) clone(db *gorm.DB) timeline {
	t.timelineDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t timeline) replaceDB(db *gorm.DB) timeline {
	t.timelineDo.ReplaceDB(db)
	return t
}

type timelineDo struct{ gen.DO }

func (t timelineDo) Debug() *timelineDo {
	return t.withDO(t.DO.Debug())
}

func (t timelineDo) WithContext(ctx context.Context) *timelineDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t timelineDo) ReadDB() *timelineDo {
	return t.Clauses(dbresolver.Read)
}

func (t timelineDo) WriteDB() *timelineDo {
	return t.Clauses(dbresolver.Write)
}

func (t timelineDo) Session(config *gorm.Session) *timelineDo {
	return t.withDO(t.DO.Session(config))
}

func (t timelineDo) Clauses(conds ...clause.Expression) *timelineDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t timelineDo) Returning(value interface{}, columns ...string) *timelineDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t timelineDo) Not(conds ...gen.Condition) *timelineDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t timelineDo) Or(conds ...gen.Condition) *timelineDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t timelineDo) Select(conds ...field.Expr) *timelineDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t timelineDo) Where(conds ...gen.Condition) *timelineDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t timelineDo) Order(conds ...field.Expr) *timelineDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t timelineDo) Distinct(cols ...field.Expr) *timelineDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t timelineDo) Omit(cols ...field.Expr) *timelineDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t timelineDo) Join(table schema.Tabler, on ...field.Expr) *timelineDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t timelineDo) LeftJoin(table schema.Tabler, on ...field.Expr) *timelineDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t timelineDo) RightJoin(table schema.Tabler, on ...field.Expr) *timelineDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t timelineDo) Group(cols ...field.Expr) *timelineDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t timelineDo) Having(conds ...gen.Condition) *timelineDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t timelineDo) Limit(limit int) *timelineDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t timelineDo) Offset(offset int) *timelineDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t timelineDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *timelineDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t timelineDo) Unscoped() *timelineDo {
	return t.withDO(t.DO.Unscoped())
}

func (t timelineDo) Create(values ...*model.Timeline) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t timelineDo) CreateInBatches(values []*model.Timeline, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t timelineDo) Save(values ...*model.Timeline) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t timelineDo) First() (*model.Timeline, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Timeline), nil
	}
}

func (t timelineDo) Take() (*model.Timeline, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Timeline), nil
	}
}

func (t timelineDo) Last() (*model.Timeline, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Timeline), nil
	}
}

func (t timelineDo) Find() ([]*model.Timeline, error) {
	result, err := t.DO.Find()
	return result.([]*model.Timeline), err
}

func (t timelineDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Timeline, err error) {
	buf := make([]*model.Timeline, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t timelineDo) FindInBatches(result *[]*model.Timeline, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t timelineDo) Attrs(attrs ...field.AssignExpr) *timelineDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t timelineDo) Assign(attrs ...field.AssignExpr) *timelineDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t timelineDo) Joins(fields ...field.RelationField) *timelineDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t timelineDo) Preload(fields ...field.RelationField) *timelineDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t timelineDo) FirstOrInit() (*model.Timeline, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Timeline), nil
	}
}

func (t timelineDo) FirstOrCreate() (*model.Timeline, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Timeline), nil
	}
}

func (t timelineDo) FindByPage(offset int, limit int) (result []*model.Timeline, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t timelineDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t timelineDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t timelineDo) Delete(models ...*model.Timeline) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *timelineDo) withDO(do gen.Dao) *timelineDo {
	t.DO = *do.(*gen.DO)
	return t
}
