// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vivianlazaras/storyteller/model"
)

func newUniverse(db *gorm.DB, opts ...gen.DOOption) universe {
	_universe := universe{}

	_universe.universeDo.UseDB(db, opts...)
	_universe.universeDo.UseModel(&model.Universe{})

	tableName := _universe.universeDo.TableName()
	_universe.ALL = field.NewAsterisk(tableName)
	_universe.ID = field.NewField(tableName, "id")
	_universe.Name = field.NewString(tableName, "name")
	_universe.Description = field.NewString(tableName, "description")
	_universe.Metadata = field.NewField(tableName, "metadata")
	_universe.Created = field.NewInt64(tableName, "created")
	_universe.LastEdited = field.NewInt64(tableName, "last_edited")

	_universe.fillFieldMap()

	return _universe
}

type universe struct {
	universeDo universeDo

	ALL         field.Asterisk
	ID          field.Field
	Name        field.String
	Description field.String
	Metadata    field.Field
	Created     field.Int64
	LastEdited  field.Int64

	fieldMap map[string]field.Expr
}

func (u universe) Table(newTableName string) *universe {
	u.universeDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u universe) As(alias string) *universe {
	u.universeDo.DO = *(u.universeDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *universe) updateTableName(table string) *universe {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewField(table, "id")
	u.Name = field.NewString(table, "name")
	u.Description = field.NewString(table, "description")
	u.Metadata = field.NewField(table, "metadata")
	u.Created = field.NewInt64(table, "created")
	u.LastEdited = field.NewInt64(table, "last_edited")

	u.fillFieldMap()

	return u
}

func (u *universe) WithContext(ctx context.Context) *universeDo { return u.universeDo.WithContext(ctx) }

func (u universe) TableName() string { return u.universeDo.TableName() }

func (u universe) Alias() string { return u.universeDo.Alias() }

func (u universe) Columns(cols ...field.Expr) gen.Columns { return u.universeDo.Columns(cols...) }

func (u *universe) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *universe) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 6)
	u.fieldMap["id"] = u.ID
	u.fieldMap["name"] = u.Name
	u.fieldMap["description"] = u.Description
	u.fieldMap["metadata"] = u.Metadata
	u.fieldMap["created"] = u.Created
	u.fieldMap["last_edited"] = u.LastEdited
}

func (u universe) clone(db *gorm.DB) universe {
	u.universeDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u universe) replaceDB(db *gorm.DB) universe {
	u.universeDo.ReplaceDB(db)
	return u
}

type universeDo struct{ gen.DO }

func (u universeDo) Debug() *universeDo {
	return u.withDO(u.DO.Debug())
}

func (u universeDo) WithContext(ctx context.Context) *universeDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u universeDo) ReadDB() *universeDo {
	return u.Clauses(dbresolver.Read)
}

func (u universeDo) WriteDB() *universeDo {
	return u.Clauses(dbresolver.Write)
}

func (u universeDo) Session(config *gorm.Session) *universeDo {
	return u.withDO(u.DO.Session(config))
}

func (u universeDo) Clauses(conds ...clause.Expression) *universeDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u universeDo) Returning(value interface{}, columns ...string) *universeDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u universeDo) Not(conds ...gen.Condition) *universeDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u universeDo) Or(conds ...gen.Condition) *universeDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u universeDo) Select(conds ...field.Expr) *universeDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u universeDo) Where(conds ...gen.Condition) *universeDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u universeDo) Order(conds ...field.Expr) *universeDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u universeDo) Distinct(cols ...field.Expr) *universeDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u universeDo) Omit(cols ...field.Expr) *universeDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u universeDo) Join(table schema.Tabler, on ...field.Expr) *universeDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u universeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *universeDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u universeDo) RightJoin(table schema.Tabler, on ...field.Expr) *universeDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u universeDo) Group(cols ...field.Expr) *universeDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u universeDo) Having(conds ...gen.Condition) *universeDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u universeDo) Limit(limit int) *universeDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u universeDo) Offset(offset int) *universeDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u universeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *universeDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u universeDo) Unscoped() *universeDo {
	return u.withDO(u.DO.Unscoped())
}

func (u universeDo) Create(values ...*model.Universe) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u universeDo) CreateInBatches(values []*model.Universe, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u universeDo) Save(values ...*model.Universe) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u universeDo) First() (*model.Universe, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Universe), nil
	}
}

func (u universeDo) Take() (*model.Universe, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Universe), nil
	}
}

func (u universeDo) Last() (*model.Universe, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Universe), nil
	}
}

func (u universeDo) Find() ([]*model.Universe, error) {
	result, err := u.DO.Find()
	return result.([]*model.Universe), err
}

func (u universeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Universe, err error) {
	buf := make([]*model.Universe, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u universeDo) FindInBatches(result *[]*model.Universe, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u universeDo) Attrs(attrs ...field.AssignExpr) *universeDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u universeDo) Assign(attrs ...field.AssignExpr) *universeDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u universeDo) Joins(fields ...field.RelationField) *universeDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u universeDo) Preload(fields ...field.RelationField) *universeDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u universeDo) FirstOrInit() (*model.Universe, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Universe), nil
	}
}

func (u universeDo) FirstOrCreate() (*model.Universe, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Universe), nil
	}
}

func (u universeDo) FindByPage(offset int, limit int) (result []*model.Universe, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u universeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u universeDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u universeDo) Delete(models ...*model.Universe) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *universeDo) withDO(do gen.Dao) *universeDo {
	u.DO = *do.(*gen.DO)
	return u
}
